### ISSUE TITLE
Logging instructions that are executed by the interpreter

### ISSUE THREAD

**Issue by cvick32** [bluealloy/revm#1008]
I want to log which bytecode instructions are actually evaluated by the EVM when a given transaction is called. The idea is to see what percentage of the total number of instructions are executed by the transaction, so that I can calculate the coverage of the transaction. 

Is this information already logged anywhere? Or would I have to add some logic to the interpreter?

Any help is greatly appreciated.

 Thanks, Cole

**Comment by rakita** [comment]
You can use Handle registers to override instructions with additional logic (logic for logging). They are set inside EvmBuilder https://bluealloy.github.io/revm/crates/revm/builder.html#appending-handler-registers.

You can check Inspector example it wraps custom inspector logic over every instruction:
https://github.com/bluealloy/revm/blob/00138a516c9705c31588aaccccd3dd28ad1cab75/crates/revm/src/inspector/handler_register.rs#L44-L57

**Comment by rakita** [comment]
Closing as answered
