### ISSUE TITLE
Rename `coinbase` to `beneficiary` in `BlockEnv`

### ISSUE THREAD

**Issue by tcoratger** [bluealloy/revm#1012]
## Issue Description

Currently, in the `BlockEnv` of the `primitives` crate, the recipient of all gas spent within a block is referred to as `coinbase`:

https://github.com/bluealloy/revm/blob/b434308a2769d8592f008a01d2555a222a4926ac/crates/primitives/src/env.rs#L432

To align with the latest yellow specifications and adhere to reth node standards, I propose renaming this field to `beneficiary`.

## Suggested Changes

- Rename the `coinbase` field to `beneficiary` in the `BlockEnv` struct.

## Context

The suggested change is in line with the evolving standards in the Ethereum ecosystem, ensuring consistency and compliance with the latest specifications. This modification will improve clarity and maintain compatibility with the broader Ethereum development community.

**Comment by rakita** [comment]
I would not break it rn but after the next release. And change is reasonable.

**Comment by PanGan21** [comment]
Hey guys, sorry I saw the comment to hold on a bit late 😅 
If it is still not required let me know and I will close the pr

**Comment by rakita** [comment]
> Hey guys, sorry I saw the comment to hold on a bit late 😅 If it is still not required let me know and I will close the pr

Lets close it, otherwise it will stay open for a few months, I apologize for the confusion

**Comment by developeruche** [comment]
Added this to this pull request #1209

**Comment by rakita** [comment]
> Added this to this pull request #1209

Please revert those, there is no need to break it right now.

**Comment by developeruche** [comment]
Reverted

**Comment by rakita** [comment]
Done as part of https://github.com/bluealloy/revm/pull/1865/files
