### ISSUE TITLE
Call depth is inconsistent in Inspector's `call` and `call_end` method 

### ISSUE THREAD

**Issue by Troublor** [bluealloy/revm#1018]
I am looking at the main branch commit b434308. 
The call depth (`context.journaled_state.depth()`) is different for the inspector's hook `call` and `call_end` regarding the same call.

For instance, suppose there is a contract-invoking transaction which does not contain any subcalls. The `call` and `call_end` hook of inspector will only be called each once for the top-level call. 
When `call` hook is called, the `context.journaled_state.depth()` is `0`, which is expected. 
However, when `call_end` hook is called, the `context.journaled_state.depth()` is `1`. This behavior is different from previous versions of revm. In revm `v3.5.0`, the `context.journaled_state.depth()` in `call_end` is also `0`.
This behavior difference is likely a regression issue introduced in the recent redesign of the evm after `v3.5.0`.

Is this change of behavior intended?

**Comment by rakita** [comment]
Behaviour should have stayed the same, it is fixed in https://github.com/bluealloy/revm/pull/1024

Thanks for reporting!

**Comment by rakita** [comment]
tested here: https://github.com/bluealloy/revm/pull/1028
