### ISSUE TITLE
Meet panic in state db

### ISSUE THREAD

**Issue by yjhmelody** [bluealloy/revm#1029]
```
thread 'main' panicked at /Users/yjhmelody/.cargo/git/checkouts/revm-bf744d8ffabcbad9/b00ebab/crates/revm/src/db/states/state.rs:267:13:
internal error: entered unreachable code: For accessing any storage account is guaranteed to be loaded beforehand
```

**Comment by yjhmelody** [comment]
Seems the guarantee is not correct

**Comment by rakita** [comment]
It should be guaranteed for normal execution, every account that is changing is first fetched from db.

Where did this happen, and can you reproduce it?

**Comment by yjhmelody** [comment]
No, not easy to reproduce it. 
But I only triggered it when using revm's API.
And I think this unreachable assumption is problematic, and there is no documentation for this trait to explain its usage.
I think we should always assume that the data in the cache may not exist

**Comment by rakita** [comment]
> No, not easy to reproduce it.

Can you explain how you use revm (mostly focused on how you use db)?

> But I only triggered it when using revm's API. 

Everything can be misused, divide with zero and you will get panic.

> And I think this unreachable assumption is problematic, and there is no documentation for this trait to explain its usage. I 
think we should always assume that the data in the cache may not exist

There is task for adding more docs, linking it here https://github.com/bluealloy/revm/issues/683

The assumption is there for a reason, if revm don't assume that, it means that we for any reason didn't load account from `db`, this would mean that we potentially have an invalid value. 

And stating that an assumption is problematic is not useful without reasoning behind it and the usage pattern that shows how to trigger it.

**Comment by yjhmelody** [comment]
I means why add assumption to the implementation not for the trait.

**Comment by rakita** [comment]
> I means why only add assumption to the implementation not to the trait.

What trait are you talking about?

**Comment by rakita** [comment]
Closing as discussion didn't lead to improvement

**Comment by yjhmelody** [comment]
Meet this again when test for optimism
