### ISSUE TITLE
`cargo bench` giving varying results (up to ~20%) on repeated runs without changes

### ISSUE THREAD

**Issue by mitchmindtree** [bluealloy/revm#1046]
Hi there! I was having a go at bench-marking safe alternatives to some of the `unsafe` code in `revm_interpreter`, and noticed that the existing benchmarks can give largely varying results even without any changes to the code.

E.g. when repeatedly running `cargo bench` just a few times, `analysis/transact/checked` appears to vary by up to ~20%, `snailtracer/transact/analysed` varies by about 7.5%, the others about 3% (on AMD 5950X, NixOS).

I haven't dug to deeply yet, but just thought I'd mention in case these benchmarks are being used to justify some of the `unsafe` optimisations going on in here, especially as they add a bit of extra work to reviewing this crate when making a decision on using it downstream.

**Comment by rakita** [comment]
Hello,

For the same results, we are running valgrind cachegrind. It is run like this:
https://github.com/bluealloy/revm/blob/main/.github/workflows/cachegrind.yml#L28-L29

In general, I am very fine with `unsafe` code that is found in revm. Would recheck unsafe pops, if they can be made in safe with the same performance. The concern of current unsafe in revm is close to none.

**Comment by rakita** [comment]
Closing it as answered
