### ISSUE TITLE
Evm can't be sent between threads

### ISSUE THREAD

**Issue by impactdni2** [bluealloy/revm#1062]
Working on 4.0 support in my application, and trying to figure out what the correct pattern is for passing an `Evm` to a thread.

My use case is I have an `Evm` that has been built (DB, BlockEnv, etc), and I'd like to simulate multiple parallel transactions (with different inputs) in that environment.

My previous (pseudo)code was:
```
fn simulate(evm: EVM) {
  some_list
    .par_iter()  // <-- rayon parallelization
    .for_each(|item| {
      let mut evm = evm.clone();
      // modify evm transaction env
      // simulate txn
    });
}
```

Looks like in 4.0, `Evm` can't be safely sent between threads.  Is there any recommended way to accomplish this?  Should I just be pulling out the DB + Env, and sending those to the thread and rebuilding a new Evm?

**Comment by impactdni2** [comment]
Am I correct in assuming that what I previously had as an `EVM` being passed around, is now better represented as just a `DB` + `Env`?  And then build a new `Evm` from those when needed?

**Comment by rakita** [comment]
I would say: `DB+ Env+ SpecId(HandlerCfg)`.

Maybe we should add function `with_context_with_handler_cfg()` to EvmBuilder and allow those to be extracted from evm (something like `evm.into_context_with_handler_cfg()`.

I would try to specify the `Emv<'static,..>` this could potentially work.

**Comment by rakita** [comment]
Added `into_context_with_handler_cfg` this would get you struct that can be send

And you can recreate Evm with EvmBuilder and with that struct

**Comment by rakita** [comment]
This PR: https://github.com/bluealloy/revm/pull/1068

**Comment by impactdni2** [comment]
This looks perfect.  Really appreciate all your hard work on revm :)

**Comment by rakita** [comment]
Closing this
