### ISSUE TITLE
Do not verify balance for Optimism deposit transactions

### ISSUE THREAD

**Issue by Wollac** [bluealloy/revm#1063]
For Optimism, deposit transactions do not have nonce or balance validation, see: [crates/primitives/src/env.rs#L207-212](https://github.com/bluealloy/revm/blob/93c7ba0ff619534751df2922e7e77671b79077ff/crates/primitives/src/env.rs#L207-212)

With #1048, this was removed without overriding the `validate_tx_against_state` in the `optimism_handle_register`. As a result, the Optimism behavior is no longer correct.

**Comment by rakita** [comment]
> Unfortunately, OP does not have a test suite comparable to Ethereum. So what we do for [zeth](https://github.com/risc0/zeth) is that we run a handful of full OP blocks and check that then the state is as expected. I think this could also make sense for revm: query and store the in and out state to execute and validate the transactions. Basically creating a manual block test similar to the eth evm tests.

This is a good idea!

**Comment by Wollac** [comment]
I can confirm that those particular blocks are now built correctly 👍 
@rakita If it helps, these were the OP blocks in our (admittedly very small) test corpus that were failing before: [105238613](https://optimistic.etherscan.io/block/105238613), [108695173](https://optimistic.etherscan.io/block/108695173)
