### ISSUE TITLE
Revert

### ISSUE THREAD

**Issue by dexloom** [bluealloy/revm#1086]
I've upgraded from 3.5 to v4 and now to v5, and I'm not 100% sure, maybe I'm doing something wrong, however it looks like emv.transact and evm.commit stopped returning Revert state.

Despite the fact that revert()  function is called and return_inner() is set to InstructionResult::Revert
SuccessOrHalt::from() gets InstructionResult::Return

**Comment by rakita** [comment]
Interesting, can you reproduce it and share the snippet?

**Comment by dexloom** [comment]
looks like false alarm. I reproduced the situation and see no problem.

**Comment by rakita** [comment]
Glad all is okay
