### ISSUE TITLE
Cant recreate evm with `ContextWithHandlerCfg`

### ISSUE THREAD

**Issue by CorrM** [bluealloy/revm#1126]
After read this issue: #1062.
I got the concept of `recreate` evm, but `ContextWithHandlerCfg` doesnt have `clone`, so what the proper way to achive multi-threading evm instance.

Also i want `db` to be shared cross all threads like when i call `insert_account_info` in thread effect all other threads.

![image](https://github.com/bluealloy/revm/assets/5868825/0cfb3c79-4ddf-44b6-9f4e-0e548f8ea2a5)

**Comment by CorrM** [comment]
After some digging
```rust
let cfg = ContextWithHandlerCfg::new(self.ctx_with_handler.context.clone(), self.ctx_with_handler.cfg.clone());
Evm::builder().with_context_with_handler_cfg(cfg).build();
```

Why i can `ContextWithHandlerCfg::new(self.ctx_with_handler.context.clone(), self.ctx_with_handler.cfg.clone())` but can't `self.ctx_with_handler.clone()` ?

I this correct way to do it ?

**Comment by rakita** [comment]
You can't as there is no `Clone` impl on `ContextWithHandlerCfg`. You are free to make PR that adds it.

Something similar to:
https://github.com/bluealloy/revm/blob/141178419d9ff8ffe5a0d6ac20523d5dcd320066/crates/revm/src/context.rs#L26-L36

**Comment by CorrM** [comment]
> You can't as there is no `Clone` impl on `ContextWithHandlerCfg`. You are free to make PR that adds it.
> 
> Something similar to:
> 
> https://github.com/bluealloy/revm/blob/141178419d9ff8ffe5a0d6ac20523d5dcd320066/crates/revm/src/context.rs#L26-L36

what about
> Also i want `db` to be shared cross all threads like when i call `insert_account_info` in thread effect all other threads.

**Comment by rakita** [comment]
> Also i want db to be shared cross all threads like when i call insert_account_info in thread effect all other threads.

This would mean creating a new struct with `RwLock` around data. Or what people do is use `DatabaseRef` to share it across the threads as it does not have mut functions. It is up to your use case
