### ISSUE TITLE
Handler Lifetime

### ISSUE THREAD

**Issue by zombie-einstein** [bluealloy/revm#1151]
Hi, I'm trying to create a struct with an `Evm` as a field and then wrap this as a pyclass using [pyo3](https://pyo3.rs/v0.20.3/class), but classes with lifetime specifiers cannot be used as Pyclasses.

 I was curious if you had any thoughts on creating a `Handler` with no lifetime specifiers, and if this seemed like a sensible thing to do, or if there was some fundamental roadblock you could forsee?

(Not suggesting this as a change to revm, just something I was considering implementing as part of our project to allow implementing a `pyclass`)

**Comment by Rjected** [comment]
Does `Evm<'static>` work?

**Comment by Rjected** [comment]
Yeah, it would be very useful if the lifetime weren't required, for example it could be used as an associated type in a trait without making that associated type a GAT

**Comment by rakita** [comment]
I would save a Context and recreate a Handler every time evm is called.

**Comment by zombie-einstein** [comment]
Thanks @rakita, do have a sense of the overhead incurred with this approach? Our simulation use-case tends to include lots of Python loops calling the EVM.

**Comment by zombie-einstein** [comment]
Great, thanks for your help
