### ISSUE TITLE
"Internal return flags should remain internal" panic can be hit with inspector

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#1154]
This panic

https://github.com/bluealloy/revm/blob/13ce01318b0c707b46430c405fb261243d281cd2/crates/revm/src/handler/mainnet/post_execution.rs#L107-L111

can be hit with an inspector that returns `Some({Call,Create}Output { result: InstructionResult::{Continue,CallOrCreate}, .. })` in `call` or `create`.

Encountered while migrating Foundry in https://github.com/foundry-rs/foundry/pull/7125/files#diff-29a0def5856966de3e16a20140415c388f71da82a37e2cfa0308c0f76085ab9fL659-R660

I'm guessing this is fine as a panic because it can only be hit with an invalid implementation or inspector.

Perhaps a better panic message can be emitted?

**Comment by rakita** [comment]
Agreed with said, we should include return flag inside panic.
