### ISSUE TITLE
Why `CreateScheme::Create2` (and salt) needs to be provided in advance? Potential Inconsistency?

### ISSUE THREAD

**Issue by wtdcode** [bluealloy/revm#1181]
Currently there are two variants for `CreateScheme` in `TxEnv` but I can't understand why it has to be known in advance, especially considering the fact that the salt can't be predicted without executing code.

More serious consequence is the inconsistency here:

https://github.com/bluealloy/revm/blob/5c0cbda7e89c518be21e2ca4cd205020853f381f/crates/revm/src/context/inner_evm_context.rs#L265-L288

For any contract creation code using `create2`, the `created_address` address here could be wrong if the given scheme is the other one. However, this can be safely avoided by using the address returned by emulating `CREATE` or `CREATE2`. I don't see any reason to use scheme in advance because checking if the destination address is zero should be pretty enough.

**Comment by wtdcode** [comment]
Reproduction code: https://github.com/paradigmxyz/reth/issues/7086#issuecomment-1987273643

**Comment by rakita** [comment]
Created issue here: https://github.com/bluealloy/revm/issues/1182
