### ISSUE TITLE
Flag to disable gas tracking

### ISSUE THREAD

**Issue by impactdni2** [bluealloy/revm#1192]
While doing some profiling of my app, I noticed gas tracking (`revm_interpreter::gas::Gas::record_cost`) is a decent amount of the cpu usage (#1 overall, 12% total).  In this particular use case, 99% of my calls into revm don't require gas tracking (as in, I don't need the result, I imagine there's some infinite-loop protection I'd be forgoing?).  

Is there any possibility of adding a flag (ex: make TxEnv.gas_limit be an Option<u64>) to disable gas accounting?

**Comment by rakita** [comment]
There was a feature in the past that disabled the gas, some people used it for tests but in the end, I decided to remove it as there was not a lot of usage traction for it
.
Gas is used as you said for infinite-loop and memory size protection, so in general, it is good to have.

**Comment by impactdni2** [comment]
Yep, I remember the feature in previous versions, but had never gotten around to actually using it (I need gas tracking in some cases, but not others, plan was to import two copies of the library and use based on that).  I think I can likely do the same thing here (just a fork that disables gas tracking).

Just odd to see the cpu usage be so high in what looks to be a very small/simple function (screenshot attached).  I imagine there's some tight loop happening on one of the contracts I'm simulating that is causing it, but I haven't been able to isolate yet.
![Screenshot_2024-03-14_11-30-39](https://github.com/bluealloy/revm/assets/53975240/a356512c-928c-4df3-b4d6-7d8282569f7f)

**Comment by rakita** [comment]
> Yep, I remember the feature in previous versions, but had never gotten around to actually using it (I need gas tracking in some cases, but not others, plan was to import two copies of the library and use based on that). I think I can likely do the same thing here (just a fork that disables gas tracking).
> 
> Just odd to see the cpu usage be so high in what looks to be a very small/simple function (screenshot attached). I imagine there's some tight loop happening on one of the contracts I'm simulating that is causing it, but I haven't been able to isolate yet.
Thanks for sharing pprof pic, it is informative!
gas calculations is called on every instruction, so it takes its time, and this is in ballpark o what i measured few years ago.

There isn't plan to support no gas flag/feature or gas block optimisation, at least not rn so I will close this Issue
