### ISSUE TITLE
Questions about the EIP3155 Spector

### ISSUE THREAD

**Issue by Pana** [bluealloy/revm#1217]
What does TracerEip3155.skip field used for?
Why the `memory` and `stack` and `return_stack` is None?

**Comment by rakita** [comment]
> What does TracerEip3155.skip field used for? Why the memory and stack and return_stack is None?

Not sure what field do you mean by `used`

`Memory` and `stack` can be big so they are omitted; if needed, you can create a PR that makes them optional and configurable.

**Comment by Pana** [comment]
The struct TracerEip3155 has a filed `skip`, it's default `value` is false, and there are no method that can set it to `true`.

Seems this filed can be omit  ?

**Comment by rakita** [comment]
> The struct TracerEip3155 has a field `skip`, it's default value is `false`, and there are no method that can set it to `true`.
> 
> Seems this field can be omitted ?

Yeah seems it can be removed
