### ISSUE TITLE
Remove `SPEC` generic usage in gas cost calculation code

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#1220]
Usage of the `SPEC` generic is unnecessary in gas calculation code as the `SpecId` is already known at compile-time in the instructions and these functions are marked with `#[inline]`, so they would get optimized the same way.

By turning the `SPEC` generic into a `SpecId` parameter:
1. most gas calculation functions can be made `const`, allowing usage in compile-time gas tables and outside of `SPEC`-generic code
2. helps a bit with compile times by reducing monomorphization bloat

`SPEC::enabled(X)` becomes `SpecId::enabled(spec, X)`.

This likely applies to more places in `revm-interpreter`, but I haven't looked too deeply into it, and I'm confident that gas calculation is a good starting place.

Examples:
- `Gas::set_final_refund` (cannot be made const due to `&mut`, rest still applies): https://github.com/bluealloy/revm/blob/fda371f73aba2c30a83c639608be78145fd1123b/crates/interpreter/src/gas.rs#L89-L92
- `gas::call_gas`: https://github.com/bluealloy/revm/blob/c203f3d033c29d26a2d02e47ffd65efa21e6dc7e/crates/interpreter/src/gas/calc.rs#L274-L287

**Comment by rakita** [comment]
> one note here is that I think we want a more flexible solution for the SpecId enum that would allow us to get rid of the duplicated op and ethereum SpecId enum. because we want to abstract away all the OP cfgs

@mattsse this is a different Issue, seems not related to this one. https://github.com/bluealloy/revm/issues/918

> Usage of the `SPEC` generic is unnecessary in gas calculation code as the `SpecId` is already known at compile-time in the instructions and these functions are marked with `#[inline]`, so they would get optimized the same way.
> 
> By turning the `SPEC` generic into a `SpecId` parameter:
> 
> 1. most gas calculation functions can be made `const`, allowing usage in compile-time gas tables and outside of `SPEC`-generic code
> 2. helps a bit with compile times by reducing monomorphization bloat
> 
> `SPEC::enabled(X)` becomes `SpecId::enabled(spec, X)`.
> 
> This likely applies to more places in `revm-interpreter`, but I haven't looked too deeply into it, and I'm confident that gas calculation is a good starting place.

In general supportive, it looks like a refactor without a lot of gains, but it can potentially be useful to const fn outside of Revm.

But would use `spec_Id.is_enabled_in(BERLIN)` as `SpecId::enabled(BERLIN, X)` can be a footgun with Spec order.
