### ISSUE TITLE
Unsupported for `create2 generates an account that already exists and has storage != 0`

### ISSUE THREAD

**Issue by yjhmelody** [bluealloy/revm#1237]
See test cases  create2collisionStorage_d0g0v0_Berlin https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stCreate2/create2collisionStorage.json
Also see https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stCreate2/create2collisionStorageFiller.json

The create2 will clean up all old state and create a new account. But the `transact` returning the `ResultAndState` not work for this case

**Comment by rakita** [comment]
wdym by not working for this case?

This case in general is not something that can happen on mainnet and need to be crafted to trigger.
And as of todays ACDE this is even specified in retroactive EIP, discusion [here](https://ethereum-magicians.org/t/eip-7610-revert-creation-in-case-of-non-empty-storage/18452).

**Comment by yjhmelody** [comment]
I mean remove the storage set by genesis.
It seems is UB？ so such test cases could be skipped？

**Comment by yjhmelody** [comment]
Are there any plans to integrate ethererum/tests?
I found that some tests failed (maybe mainly due to inconsistent calculation of state root, which has nothing to do with the revm level)

**Comment by rakita** [comment]
> Are there any plans to integrate ethererum/tests? I found that some tests failed (maybe mainly due to inconsistent calculation of state root, which has nothing to do with the revm level)

State test from ethereum/tests are run at every revm PR, this has a case for about two years now. For the test that you mentioned, revm is passing it and calculating the state root correctly.

> I mean remove the storage set by genesis when create the same address
> 
> It seems is UB？ so such test cases could be skipped？

That test is not skipped. Please read discussion that i linked. This would require a hash collision to trigger, if you can trigger a hash collision, there are a lot more assumptions that are going to break.
