### ISSUE TITLE
Is there any reason to stick to `std::collections::*`

### ISSUE THREAD

**Issue by CorrM** [bluealloy/revm#1246]
Is there any reason to stick to `std::collections::*` instead of just using `hashbrown`? even if the `std` feature is enabled?
As `hashbrown` is faster in most cases.
https://github.com/bluealloy/revm/blob/81b65dd841cc4a5e3b1df1f4d0d1a23fd0c4132e/crates/primitives/src/lib.rs#L32-L39

**Comment by rakita** [comment]
It is about HashMap hashing algo, hashbrown does not have hashddos protection.
