### ISSUE TITLE
possible compatibility issue with running graph node against anvil

### ISSUE THREAD

**Issue by davisshaver** [bluealloy/revm#135]
I am trying to get a local graph node running against anvil for https://github.com/holic/web3-scaffold/pull/27.

While compatibility issues with this integration are already being tracked here https://github.com/graphprotocol/graph-node/issues/3640 and here, I ran into a separate error message that I wanted to file for discoverability. I'm not sure if it's an revm bug or an issue with my config.

Here's an example error message:

```
Jun 25 18:45:09.348 INFO Possible reorg detected, retrying, error: failed to process trigger: block #2 (0x93c4…3d1a), transaction 4e58144bf7b4a22f3149b88b7d6a2701333098cf26a70449dc386b62b993f658: Ethereum node returned an error when calling function "tokenURI" of contract "ExampleNFT": RPC error: Error { code: InternalError, message: "EVM error CallerGasLimitMoreThenBlock", data: None }
wasm backtrace:
    0: 0x2d09 - <unknown>!src/mapping/handleTransfer
, block_hash: 0x93c44cc11644bd2f10c1edb02f5c9c5b03ee16ad96a43f89efcf69d69eb63d1a, block_number: 2, sgd: 1, subgraph_id: QmXt9LHphz6mEJLv4tmLkUr1QnZkwc8CCLSVcRndZNrZFU, component: SubgraphInstanceManager
```

**Comment by rakita** [comment]
This error is from revm: `EVM error CallerGasLimitMoreThenBlock` called here: https://github.com/bluealloy/revm/blob/eb7af7080dd89d5d75e9438395d02ee623651135/crates/revm/src/evm_impl.rs#L68-L71
It is one of the dummy checks done before EVM execution. If these are custom tx, gas_limit is maybe set quite big or block gas limit is set very small or not set at all. 
@davisshaver how do you call anvil and how do you configure it. I am not familiar with it but can probably give some hints.
@mattsse you probably know better than me about this.

**Comment by mattsse** [comment]
there was a gas limited-related fix yesterday https://github.com/foundry-rs/foundry/pull/2117

the default block gas limit should be 30M

https://github.com/foundry-rs/foundry/blob/master/anvil/src/config.rs#L286

**Comment by davisshaver** [comment]
Thanks @mattsse and @rakita! I ran `foundryup` and then called anvil with `--gas-limit 50000000 ` to match [what's used in graph-node](https://github.com/graphprotocol/graph-node/blob/master/NEWS.md#ethereum), and things are working as expected now. 🎉
