### ISSUE TITLE
Trying to call `transact_commit` on a block without transactions return an error

### ISSUE THREAD

**Issue by rllola** [bluealloy/revm#1370]
I am trying to commit a block but that has no transaction so it will take into account the `coinbase` reward. But when I call commit it return an error.

See the logs 
```
[src/main.rs:119:9] tx = TxEnv {
    caller: 0x0000000000000000000000000000000000000000,
    gas_limit: 18446744073709551615,
    gas_price: 0x0_U256,
    transact_to: Call(
        0x0000000000000000000000000000000000000000,
    ),
    value: 0x0_U256,
    data: 0x,
    nonce: None,
    chain_id: None,
    access_list: [],
    gas_priority_fee: None,
    blob_hashes: [],
    max_fee_per_blob_gas: None,
}
[src/main.rs:123:9] result = Err(
    Transaction(
        CallerGasLimitMoreThanBlock,
    ),
)
```

I tried to call `evm.tx()` to see if something was in it and I have empty transaction but with the max `gas_limit` which I think could be the issue ? Any way I could explicitly say there is no transactions ?

I am still trying to understand how to use revm so sorry if my question is naive.

**Comment by rakita** [comment]
Recm is used to execute transaction, not blocks. Coinbase reward after PoS transition is given only if transaction are present.

**Comment by rllola** [comment]
Thanks @rakita. If I may bother you with another question...

I am trying to replay all the blocks from mainnet from start so the first blocks are PoW and I need to register the coinbase reward. So now I am calculating the reward and I am using `insert_account_info` to update the account balance. Would you say it is correct approach ?
