### ISSUE TITLE
Transactions Revert

### ISSUE THREAD

**Issue by germankuber** [bluealloy/revm#1381]
I am simulating transaction that always rever on my revm code. 
I am using the same code that is in the example of "[uniswap_v2_usdc_swap.rs](https://github.com/bluealloy/revm/blob/main/examples/uniswap_v2_usdc_swap.rs)"

I am chaging the calle, to, data, value.

The transaction always revert. But If i execute the same with froundry the transaction execute succefully.
And of course the transaction is in the blockchain

Tx_hash : 0x8dbbd44fe68eaa387425a402b0f91f0fa93e752f240eb71d883e97db08b340b5

**Comment by rakita** [comment]
Chatted in tg group, this is not related to Revm.

Would assume previous tx are not executed as it works with cast
