### ISSUE TITLE
Modify `JournaledState` to support stateless witness

### ISSUE THREAD

**Issue by frisitano** [bluealloy/revm#1439]
## Overview
We need stateless witnesses to use revm (and reth) as an execution engine for the type 1 prover which is under development at Polgyon and by association the shared sequencer we are developing at Fractal.

## Problem
The current implementation of `JournaledState` has checkpoint reverts.  When the journaled state is reverted to some checkpoint then all database lookups will be reverted and as such when the `JournaledState` object is finalised it does not include these reverted lookups. We can see as a consequence of this when we run the `PrestateTracer` these lookups which have been reverted are not included in the trace. This is problematic as in these cases the witness generated by the tracer is not complete.

## Solutions
We could modify the way in which the `JournaledState` object handles revision for database loads such that the reverted lookups are retained. Some drafts of how this could be implemented can be seen here:
https://github.com/bluealloy/revm/pull/1437
https://github.com/bluealloy/revm/pull/1438

However, I'm not sure if there will be any upstream downstream consequences of such a change or if resistance to this change would be too large?  An alternative would be to introduce a trait for `JournaledState` with a default implementation, this being the one that is currently used. We could then introduce a builder (`pub fn with_journaled_state(self, journaled_state: JournaledStateT) ...`) on the `InnerEvmContext` (and parent objects) to override the default `JournaledState` object.

Some discussion on the preferred approach would be appreciated.

**Comment by rakita** [comment]
Supportive of this, will review and merge one of the options.

**Comment by rakita** [comment]
Closed in https://github.com/bluealloy/revm/pull/1437
