### ISSUE TITLE
EOF: change oob behavior of RETURNDATALOAD and RETURNDATACOPY

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1473]
Change is here: https://github.com/ipsilon/eof/pull/90

TODO put in this PR: https://github.com/bluealloy/revm/pull/1472

**Comment by jpgonzalezra** [comment]
@rakita Can I take it ?

**Comment by rakita** [comment]
Go for it

**Comment by rakita** [comment]
Closed in #1476
