### ISSUE TITLE
on EXTCODEHASH load bytecode and check if it is EOF

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1483]
if EXTCODEHASH target is an account with EOF bytecode, we need to return `0x9dbf3648db8210552e9c4f75c6a1c3057c0ca432043bd648be15fe7be05646f5`

This means that extcodehash would need to load account bytecode and check first byte of it.

https://github.com/ipsilon/eof/blob/main/spec/eof.md#modified-behavior
```
When executed from a legacy contract, if the target account of EXTCODEHASH is an EOF contract,
then it will return 0x9dbf3648db8210552e9c4f75c6a1c3057c0ca432043bd648be15fe7be05646f5
(the hash of EF00, as if that would be the code).
```

**Comment by jpgonzalezra** [comment]
Can I tackle it?
