### ISSUE TITLE
Unify `alloy-eips` and `revm-primitives` KZG implementations

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#1553]
After https://github.com/bluealloy/revm/pull/1552 is merged we should use `alloy-eips` for our KZG needs. CC @Wodann

**Comment by rakita** [comment]
Those should be pushed to `c-kzg` lib as they are lib specific.

**Comment by rakita** [comment]
done

**Comment by mattsse** [comment]
based
