### ISSUE TITLE
Use cfg codesize limit for EOFCREATE

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1580]
Currently, it is set to consensus size but it should be dependent on env.cfg.

**Comment by peyha** [comment]
Would love to start working on EOF through this issue :)

**Comment by peyha** [comment]
seems like it was solved by #1606, are there other EOF related issues ?

**Comment by rakita** [comment]
Yep, this PR is finished.

There is a task for sticker validation if you want to take a stab at it: https://github.com/bluealloy/revm/issues/1618
