### ISSUE TITLE
Factor out `*COPY` common code

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#1637]
All `*COPY` operations have the same inputs, execute the same operation, and have the same gas cost (except for `EXTCODECOPY`); the only difference is which buffer they copy from. This code can be factored out for less code duplication.

**Comment by peyha** [comment]
I'll tackle this one

**Comment by cairoeth** [comment]
@rakita this was completed in https://github.com/bluealloy/revm/pull/1799 or is there anything missing?
