### ISSUE TITLE
EthersDB::new() returning None in single-threaded environment (tokio::test)

### ISSUE THREAD

**Issue by flarocca** [bluealloy/revm#1654]
Hi! I am trying to update from version `8.0.0` to the `latest` and I started to get `None` when running the integration tests.

### Context
Our main application runs using `#[tokio::main]` without any issues with both libraries (`8.0.0` and `12.1.0`). The application spawns a new thread for every transaction in the block to perform different kind of simulations, we create a new instance of `EthersDB` in each thread.
Additionally, we use some channels to communicate different processes of the application

### Problem
We also run a suite of  integration tests using `#[tokio::test]` that try to avoid mocking so that we can have as closely as possible real environments. We only mock calls to the web3 provider, the rest remains the same as the production code.
Since each thread runs as `tokio::runtime::RuntimeFlavor::CurrentThread` when using `tokio::test` macro, we started to get `None` responses from `EthersDB::new()` due to the check added [here](https://github.com/bluealloy/revm/blob/8eaff99234aca42955345e2775ef11e24e2c0339/crates/revm/src/db/ethersdb.rs#L24).

```rust
pub fn new(client: Arc<M>, block_number: Option<BlockId>) -> Option<Self> {
    let rt = match Handle::try_current() {
        Ok(handle) => match handle.runtime_flavor() {
            tokio::runtime::RuntimeFlavor::CurrentThread => return None,
            _ => HandleOrRuntime::Handle(handle),
        },
        Err(_) => return None,
    };

    // rest of the code
}
```

### Challenge
Even though there is an alternative to create an instance of `EthersDB` from a `tokio::runtime` (`EthersDB::with_runtime(...)`), that implies using different building mechanisms depending whether it is a test or the real application, which will require quite a
significant amount of refactoring.
Additionally, since we also use some Channels to send events between different parts of the application, it would also force us to refactor parts of the application not strictly related to `EthersDB` usage just for testing purposes.
Maybe we are not using it correctly at all.

### Open questions

1. What is the reason behind the validation to prevent single-threaded scenarios?
2. What is the best way to use EthersDB to simulate transactions?
3. What is the best way to use EthersDB for integration testing like mine?

### Working example

```rust
#[tokio::test]
async fn demo_test() {    
    let provider = "https://eth-mainnet.g.alchemy.com/v2/{API_KEY}";
    let client = Arc::new(Provider::<Http>::try_from(provider).unwrap());
    let mut set = JoinSet::new();

    // This process simulates how a transaction is executed. For each transaction
    // we spawn a new task that executes the transaction against a fresh EthersDB.
    for _transaction in 1..4 {
        let cloned_client = client.clone();
        set.spawn(async move {
            // Select a specific block for simulation
            let block_id = Some(BlockId::Number(
                ethers_core::types::BlockNumber::from_str("latest").unwrap(),
            ));
            let db = EthersDB::new(cloned_client, block_id);

            assert!(db.is_some(), "Failed to create EthersDB");
        });
    }

    while let Some(res) = set.join_next().await {
        assert!(res.is_ok());
    }
}
```

Thanks a lot for the help!

**Comment by rakita** [comment]
In Future, I am thinking of removing EthersDb and moving AlloyDb to examples, so as not to be confused with the main db crate.
