### ISSUE TITLE
Expose `gas_refunded` in EVM

### ISSUE THREAD

**Issue by ngotchac** [bluealloy/revm#167]
Hi,

For a private project, I would need to get access to the `gas_refunded` value computed during the finalization phase of a transaction's execution. This is useful, in conjunction with the `gas_used` to better estimate the required gas of a transaction.

I already have it implemented [here](https://github.com/bluealloy/revm/commit/06723ae820953e42950d3ce25ba92c1a7d96ac81), but it introduces some changes to this crate's API, which is why I didn't open a PR. I'm not sure what's the best path here...

**Comment by rakita** [comment]
If project is private, I would need you and your extended family to sign the pack of publicness ( just kidding).

API should be changed to return this value, would probably introduce a new struct as this would be the 6th output field.

**Comment by ngotchac** [comment]
Aha yeah sorry I don't really have a choice about its publicness :/
Yeah I was also thinking about returning a `struct` since the tuple is getting quite big. Should I make a PR then?

**Comment by rakita** [comment]
go for it

**Comment by rakita** [comment]
@ngotchac thank you for contributing
