### ISSUE TITLE
error[E0658] when compiling

### ISSUE THREAD

**Issue by ChainsightLabs** [bluealloy/revm#170]
error[E0658]: deriving `Default` on enums is experimental
  --> C:\Users\Ben\.cargo\registry\src\github.com-1ecc6299db9ec823\revm-1.9.0\src\db\in_memory_db.rs:41:24
   |
41 | #[derive(Debug, Clone, Default)]
   |                        ^^^^^^^
   |
   = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `revm` due to previous error

**Comment by rakita** [comment]
`rustup update` should fix this.
