### ISSUE TITLE
EIP-7702 inconsistency

### ISSUE THREAD

**Issue by mrLSD** [bluealloy/revm#1714]
## Description

According to [EIP-7702 Specification](https://eips.ethereum.org/EIPS/eip-7702#specification) it's several inconsistencies:

➡️  In validation [Step 1](https://github.com/bluealloy/revm/blob/main/crates/revm/src/handler/mainnet/pre_execution.rs#L58) there is no validation step [Behavior 1.](https://github.com/bluealloy/revm/blob/main/crates/revm/src/handler/mainnet/pre_execution.rs#L58). 
```
authority = ecrecover(keccak(MAGIC || rlp([chain_id, address, nonce])), y_parity, r, s]
```
It's a vector of attack.

➡️  [Step 4](https://github.com/bluealloy/revm/blob/main/crates/revm/src/handler/mainnet/pre_execution.rs#L83) - accodingto specification `Nonce` is required filed, and it's impossible situation for `Option<None>`

➡️  [Step 6](https://github.com/bluealloy/revm/blob/main/crates/revm/src/handler/mainnet/pre_execution.rs#L90) just wrong (in Specification it's `step 7`):
```
Set the code of authority to be 0xef0100 || address. This is a delegation designation.
```

➡️  A nit: Behavior steps number in the specification and in comments are different, and it's confusing.

➡️  `Step 8` from Specification just absent:
```
Increase the nonce of authority by one.
```

## Main logic of EIP-7702

It looks, like after [creating list](https://github.com/bluealloy/revm/blob/main/crates/revm/src/handler/mainnet/pre_execution.rs#L116) it doesn't used for [Delegation Designation logic](https://eips.ethereum.org/EIPS/eip-7702#delegation-designation)

## Unclearity

It's unclear intention of:
```
pub enum AuthorizationList {
    Signed(Vec<SignedAuthorization>),
    Recovered(Vec<RecoveredAuthorization>),
}
```
It looks overcomplicated for such simple simple structure (according to Spec) like `authorization_list`.

## Relations

Related to #1268

**Comment by rakita** [comment]
Current EIP-7702 changes were needed for devnet-1 and devnet-2 devnets as agreed by core devs.

New changes are coming in effecy in devnet-3 (expected in week or two) and those changes are made in PR here https://github.com/bluealloy/revm/pull/1695.

That PR will be merges in few days after they pass eth statetests. Statetests for newest EIP version was made today.
