### ISSUE TITLE
Use TestAuthorization and skip decoding of eip7702 tx

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1728]
In this PR we have decoded tx bytes to extract AuthorizationList.

a better way would be to use values from json as we are already parsing them, it is needed to cast them to RecoveredAuthorization and test/debug this.

**Comment by royvardhan** [comment]
Hi @rakita I am down to attempt this but have some questions: 
1. I can read these tests at alloy-eips: https://github.com/alloy-rs/eips/blob/3136c2883e8d59cd1ac5b004dffb8bc826f0fc03/crates/eip7702/src/auth_list.rs#L302, would you like me to extend it with extracting values directing from json and then assert them?
2. Or would you like to add new tests in https://github.com/bluealloy/revm/blob/main/crates/primitives/src/eip7702/authorization_list.rs where we parse values from json and test them?

**Comment by royvardhan** [comment]
@rakita Awaiting your response, thanks!

**Comment by rakita** [comment]
We should remove this file: https://github.com/bluealloy/revm/blob/main/bins/revme/src/cmd/statetest/models/eip7702.rs
And use this struck: https://github.com/bluealloy/revm/blob/d38ff452714e1c4a17cf0fbdaa4913f6d61033c4/bins/revme/src/cmd/statetest/models/mod.rs#L139
