### ISSUE TITLE
Handler Example: use ERC-20 token to pay for gas 

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1782]
It is one of the interesting use cases where gas can be paid from ERC-20 account.

Handler that needs to be overwritten:
* `deduct_caller` from `PreExecution`: https://bluealloy.github.io/revm/crates/revm/handler.html#preexecutionhandler
* `reimburse_caller` and `reward_beneficiary` from post execution: https://bluealloy.github.io/revm/crates/revm/handler.html#postexecutionhandler
* validation check for Account here: `validate_tx_against_state` https://bluealloy.github.io/revm/crates/revm/handler.html#validationhandler.

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by rakita** [comment]
@royvardhan has amazing amount of progress here: https://github.com/royvardhan/revm/pull/1 it needs to be ported to new handler on main

**Comment by royvardhan** [comment]
> @royvardhan has amazing amount of progress here: [royvardhan#1](https://github.com/royvardhan/revm/pull/1) it needs to be ported to new handler on main

Working on the new handler example
