### ISSUE TITLE
Manually impl `PartialEq` for `Reverts`

### ISSUE THREAD

**Issue by Rjected** [bluealloy/revm#1813]
In reth's invalid block hooks, we first compare the invalid block's `BundleState` to a re-executed version, then use `serde_json` to serialize `BundleState` and save it as JSON. Because the reverts are unsorted, this leads to equivalent `BundleState`s being seen as not equal. Instead, there should be a comparison API for `Reverts` that returns `true` if the reverts have the same contents, regardless of ordering.

**Comment by 0xurb** [comment]
@Rjected like this?

```rust
    /// Compares two `Reverts` for equality, sorting the internal `Vec`s in place.
    pub fn unordered_eq(&mut self, other: &mut Self) -> bool {
        // Sort inner vectors by Address in place
        self.sort();
        other.sort();

        // Compare sorted structures for equality
        self.0 == other.0
    }
 ```
