### ISSUE TITLE
EIP-7742: Replace usage of EIP-4844 constants with dynamic values

### ISSUE THREAD

**Issue by onbjerg** [bluealloy/revm#1873]
Similar to https://github.com/alloy-rs/alloy/issues/1709, we now have to calculate excess blob gas not with constants, but with values passed in from CL (or the header in historical sync). This is because the CL now determines target/max for blob count.

Anything in revm that relies on hardcoded target/max (currently 3/6) needs to use a dynamic value passed in in `BlockEnv`.

The logic is the exact same as in EIP-4844, with the only change being that we no longer use hardcoded constants.

**Comment by rakita** [comment]
Done in: https://github.com/bluealloy/revm/pull/1899 and https://github.com/bluealloy/revm/pull/1900
