### ISSUE TITLE
Example of smart contract execution?

### ISSUE THREAD

**Issue by MathieuDutSik** [bluealloy/revm#1875]
I am trying to make smart contract calls on REVM instances. I want to have a smart contract constructor and then call a function of the smart contract. The constructor takes an argument and emits an event. Then the function call should emit an event as well.

I have the constructor working correctly and emitting an event as expected. However, the function call does not work correctly. The return is `ExecutionResult::Success::Stop`. I dig with print statements and indeed the `InstructionResult::Stop` is created, but no instruction is executed at all.

I was looking in REVM for one smart contract example. There are several tests around revert, gas, refund, precompiles but as far as I can tell no test of the `tx.data`. Could we have some examples about how to build transactions and testing of the emitted events. If that is not possible, could we have an exact reference about how to do it.

**Comment by rakita** [comment]
Pozdrav, there is contract deployment example that should you how to deploy and use bytecode: https://github.com/bluealloy/revm/blob/main/examples/contract_deployment/src/main.rs

I would try to figure out what bytecode you want to call, maybe you are targeting wrong address.

**Comment by MathieuDutSik** [comment]
That was good advice. Indeed, I was sending data to the wrong address.

However, the examples that you gave had `tx.data = Default::default()`. That is a very specific case (I do not know which one since as far as I know the first 4 bytes are for the hash of the function called). So maybe adding a more realistic case could be helpful.

Another point is that the `TxEnv` is defined as
```
    /// The data of the transaction.
    pub data: Bytes,
```
Maybe adding a link to where it is built could be helpful.

**Comment by rakita** [comment]
There are more examples. This is how uniswap is called and it shows how you can generate input data with sol! : https://github.com/bluealloy/revm/blob/main/examples%2Funiswap_get_reserves%2Fsrc%2Fmain.rs
