### ISSUE TITLE
Make k256 default precompile

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1913]
This bench shows that k256 is faster than secp256k1 (C version): https://github.com/tarcieri/rust-secp256k1-ecdsa-bench. We should default to using it.

**Comment by aguzmant103** [comment]
@rakita why not [rust-secp256k1](https://github.com/rust-bitcoin/rust-secp256k1) then?

Also happy to take a stab at it! 🙋‍♂️

**Comment by Pana** [comment]
k256 and libsec256k1 are implemented in pure Rust

**Comment by FredCoen** [comment]
once https://github.com/bluealloy/revm/pull/1915 is merged should it default to [rust-secp256k1](https://github.com/rust-bitcoin/rust-secp256k1) and not k256?

**Comment by rakita** [comment]
@aguzmant103 you are right I made mistake here, from graph `[rust-secp256k1](https://github.com/rust-bitcoin/rust-secp256k1)` is fastest and should stay as default.

Will close this issue as @FredCoen is adding `libsec256k1` support in #1915.
