### ISSUE TITLE
Integrate rust-secp256k1

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1914]
We should integrate it inside Precompiles under the feature flag.  https://github.com/tarcieri/rust-secp256k1-ecdsa-bench

**Comment by henopied** [comment]
Doesn't that benchmark show it being _slower_ than the others?

**Comment by henopied** [comment]
I think Parity's implementation is [libsecp256k1](https://github.com/paritytech/libsecp256k1) (the slowest.) Aren't the faster ones the two that are already implemented?

**Comment by rakita** [comment]
> I think Parity's implementation is [libsecp256k1](https://github.com/paritytech/libsecp256k1) (the slowest.) Aren't the faster ones the two that are already implemented?

Correct, i made a mistake here and will edit main post.
