### ISSUE TITLE
Remove create address collision check with precompile address

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1925]
Rm this: https://github.com/bluealloy/revm/blob/ca85e67d1fd6122551bb52f8d2e4c6b8d2deadf1/crates/handler/src/frame.rs#L272
And this: https://github.com/bluealloy/revm/blob/ca85e67d1fd6122551bb52f8d2e4c6b8d2deadf1/crates/handler/src/frame.rs#L396

**Comment by Gerson2102** [comment]
Hello. Can I work on this one?
