### ISSUE TITLE
EIP-2537: BLS precompile gas repricing

### ISSUE THREAD

**Issue by rkrasiuk** [bluealloy/revm#1942]
## Description

Update BLS precompile gas pricing:

- [ ] [Gas pricing pairing operations](https://github.com/ethereum/EIPs/pull/9098)
- [ ] [Gas pricing MAP, MUL and ADD operations](https://github.com/ethereum/EIPs/pull/9097)
- [ ] [MSM gas repricing](https://github.com/ethereum/EIPs/pull/9116)

**Comment by rakita** [comment]
Additionaly g1_mul and g2_mul were removed and addresses were shifted

**Comment by rakita** [comment]
done https://github.com/bluealloy/revm/pull/1951
