### ISSUE TITLE
Devnet 5

### ISSUE THREAD

**Issue by rkrasiuk** [bluealloy/revm#1943]
## Description

Implement all changes for devnet 5.

- [x] https://github.com/bluealloy/revm/issues/1942
- [x] https://github.com/bluealloy/revm/issues/1944
- [x] https://github.com/bluealloy/revm/issues/1945

**Comment by rakita** [comment]
done

**Comment by rakita** [comment]
Changes for devnet-6:
https://github.com/ethereum/EIPs/pull/9248
https://github.com/ethereum/EIPs/pull/9250
