### ISSUE TITLE
What is the root cause of the performance improvement from 0.19.0 to 0.20.0

### ISSUE THREAD

**Issue by ImJeremyHe** [bluealloy/revm#214]
I mocked 10000 transactions to check the performance for revm. After bumping revm to version 0.20.0, I found there is a great improvement.
I have checked the release log, but still have no clue.
Can anyone help me find out what is the root cause? Thanks!

**Comment by rakita** [comment]
Initialization was not optimized earlier and precompile "Loading" was done in the not fastest way, So I optimized that part and it became faster.
This part: https://github.com/bluealloy/revm/blob/b19acaac70222c7bb0c4b75b5c2ea1b5c44b27b9/crates/revm/src/evm_impl.rs#L167-L181 was replaced with  this https://github.com/bluealloy/revm/blob/aa39d64fc3f14ba381c5d244edb3a1f02805e521/crates/revm/src/evm_impl.rs#L204-L208
Cached precompile HashMap here gave speed up: https://github.com/bluealloy/revm/commits/main

This is good comparison of simple SM call that does nothing that is x4 faster than 1.8: https://github.com/cl2089/rust-evm-bench 

An additional change is related to Bytecode analysis. You can read about it here: https://github.com/bluealloy/revm/issues/121

**Comment by ImJeremyHe** [comment]
Thanks for your reply! I will take a further look for it.

**Comment by rakita** [comment]
If you want to see where exactly the processing went I would recommend doing `cargo flamegraph` and comparing commits from this branch: https://github.com/cl2089/rust-evm-bench it is very visually evident
