### ISSUE TITLE
Add Axon to project list

### ISSUE THREAD

**Issue by samtvlabs** [bluealloy/revm#229]
[Axon](https://github.com/axonweb3/axon) is a frame work for spinning up EVM compatible side chains. They currently use the [revm](https://github.com/axonweb3/axon/blob/main/core/executor/Cargo.toml#L50). It would be great to add them to the project list.

**Comment by rakita** [comment]
@samtvlabs Axos is not using revm but sputnikvm (evm crate). They included revm only for benchmark: https://github.com/axonweb3/axon/blob/162e17975db7273871fa90b28349e977453d2f7c/core/executor/benches/bench_vm.rs#L71-L98

@ImJeremyHe, @KaoImin in this test i was getting x4-5 time speed on revm: https://github.com/cl2089/rust-evm-bench/pull/2
it is little bit different benchmark where only call is benched not whole setup.
In axon case you are setting it up and additionally creating merkle trie and hashing in general uses a lot of time, if you remove that it should probably align more with rust-evm-bench

**Comment by rakita** [comment]
Will close this, but will be glad to add them when they start using revm :)
