### ISSUE TITLE
Add benchmarking tool

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#23]
This seems like a great way to compare all evm's by opcode:
https://github.com/imapp-pl/gas-cost-estimator

additionaly we could add testing benchmark of our own so that we have faster build/test iteration when optimizing things.

**Comment by stan7123** [comment]
Hi,
I'm new to Rust but I'm trying to write simple code to benchmark arbitrary bytecode on REVM.
I saw examples that are already in the repo but they all assume creating a contract and running a transaction. Is there a simpler way to just run raw bytecode on EVM? Could you provide a simple example of how to do it?

**Comment by stan7123** [comment]
I managed to put the bytecode into the contract object and I'm running Interpreter with transaction data set to an empty string.
Seems to be executing opcodes correctly.

**Comment by rakita** [comment]
Will close this as it is an old issue,
