### ISSUE TITLE
Avalanche txs failing incorrectly when simulated locally

### ISSUE THREAD

**Issue by gd-0** [bluealloy/revm#241]
Hey all. Are there any known issues simulating txs on chains other than Ethereum? 

For example, I am trying to simulate this Avalanche tx: https://snowtrace.io/tx/0xc924c3e0bd6c56ce69afb638f84820260e80d4dae30ce4e6b87476f9bb52b654. On chain the tx is successful but locally it is failing with: "Second mul check failed". 
This is the code location for the revert: https://snowtrace.io/address/0xd5d517abe5cf79b7e95ec98db0f0277788aff634#code#F8#L464. It uses the Ecrecover precompile so maybe it has something to do with that? Is the chain id hard coded as 1 somewhere inside the REVM precompile?

Here is the code that I am using:
```
// Fetch tx details
let rpc_caller = RpcCaller::new("https://api.avax.network/ext/bc/C/rpc".to_string());
let mut tx: ethers::types::Transaction = rpc_caller.get_transaction_by_hash(H256::from_str("0xc924c3e0bd6c56ce69afb638f84820260e80d4dae30ce4e6b87476f9bb52b654").unwrap()).unwrap();
tx.chain_id = Some(U256([43114,0,0,0]));  // for from address recovery

// Init evm
let mut evm = revm::new();
evm.db = Web3DB::new("https://api.avax.network/ext/bc/C/rpc", Some(tx.block_number.unwrap().as_u64() - 1));

// Build env and simulate
evm.env = Env::default();

evm.env.block.number = U256::from(tx.block_number.unwrap().as_u64());
evm.env.block.difficulty = ONE_BIGINT;
evm.env.block.timestamp = U256::zero();
evm.env.block.basefee = U256([25000000000,0,0,0]);
evm.env.block.gas_limit = U256([8000000,0,0,0]);

evm.env.tx.chain_id = Some(43114);
evm.env.tx.caller = tx.recover_from().unwrap();
evm.env.tx.transact_to = TransactTo::Call(tx.to.unwrap());
evm.env.tx.nonce = Some(tx.nonce.as_u64());
evm.env.tx.value = tx.value;
evm.env.tx.data = tx.input.0;
evm.env.tx.gas_limit = tx.gas.as_u64();
evm.env.tx.gas_price = tx.gas_price.unwrap();
evm.env.tx.gas_priority_fee = tx.max_priority_fee_per_gas;
evm.env.tx.access_list = Vec::new();

let result = evm.transact();
```

Here is another example of a tx that fails locally: 0xce22b6b3b20dddc59f1b7e9f281b824e7cbf6fb5faee585e5da4f5e11ec10b98. Local revert reason: "LOP: bad signature". Code failure location: https://snowtrace.io/address/0x0f85a912448279111694f4ba4f85dc641c54b594#code#F8#L20

**Comment by gd-0** [comment]
Issue has now been solved. Fixes were:

1) Adding the chain_id to "CfgEnv"
```evm.env.cfg.chain_id = U256([43114,0,0,0]);```

2) Removing the check inside this if statement:
https://github.com/bluealloy/revm/blob/9f8cdbd5cbeb831c1f6bb28b913e83b2a467700b/crates/revm/src/db/web3db.rs#L111

**Comment by rakita** [comment]
Hey thank you for reporting this.

I didn't expect this would be a problem, there is PR something related to that
