### ISSUE TITLE
Tx unexpectedly reverts with "out of gas" reason

### ISSUE THREAD

**Issue by Owen66** [bluealloy/revm#255]
Hi,

When processing the below tx with the revm I get an out of gas revert?
https://snowtrace.io/tx/0x5d9999e9e8ccdea2d87736cc39c38f51863f6f23169ac32ef2d9a1842aa94c23

Gas limit on the tx is 348,243 and gas used is 348,243. Seems strange to me that it fails with revm but doesn't fail on avalanche?
Avalanche just use a copy of geth for this stuff afaik.

**Comment by gd-0** [comment]
Just to add some extra info to this.

It seems like every "withdraw" call to this contract: https://snowtrace.io/address/0xf6ccf601bd024612aaf85440153c2df0524e4607 (same fn and contract called by the 0x5d99.. tx linked above) costs 3 GAS more using the REVM compared to Avalanche Coreth.

**Comment by rakita** [comment]
That is suspicious

**Comment by gd-0** [comment]
Some more info:

Here are 4 txs that cost exactly 3 extra gas using the revm vs Avalanche Coreth/ Sputnik EVM:
```
- 0x2a592ab55d9823aa6e25386a361569ae74c274d5352214632505daefdfd885c3
- 0xe6f7f5fe3287e922bf6ecc17104d243bb6c9234574bba2b01c90b90fd883a77f
- 0x5d9999e9e8ccdea2d87736cc39c38f51863f6f23169ac32ef2d9a1842aa94c23
- 0x832e5a4b5f3596eeba4c88aef567a73fd50cebb5d2d46a4710ee1ef1e36428fc
```

I ran each of these txs with REVM and Sputnik logging each opcode that was used and the number of time each was used. Here are the differences:

```
1) 
Different counts! Opcode: 91. REVM count: 4756. SPUTNIK count: 4700
REVM contains an extra opcode: 254. COUNT: 9
Different counts! Opcode: 0. REVM count: 10. SPUTNIK count: 8 

2) 
Different counts! Opcode: 91. REVM count: 1465. SPUTNIK count: 1446
REVM contains an extra opcode: 254. COUNT: 2
Different counts! Opcode: 0. REVM count: 10. SPUTNIK count: 8

3) 
Different counts! Opcode: 0. REVM count: 8. SPUTNIK count: 6
REVM contains an extra opcode: 254. COUNT: 9
Different counts! Opcode: 91. REVM count: 5361. SPUTNIK count: 5294

4)
REVM contains an extra opcode: 254. COUNT: 3
Different counts! Opcode: 0. REVM count: 14. SPUTNIK count: 12
Different counts! Opcode: 91. REVM count: 3480. SPUTNIK count: 3430
```

Note: I also ran this for txs that get the gas cost exactly correct and the only difference i saw was in the "91" opcode so maybe there is something up with my logging for that? Seems strange that the 254 (INVALID) opcode is appearing for failed txs and there are always 2 extra "0" (STOP) opcodes.

Does anyone have any ideas?

**Comment by rakita** [comment]
`91` is jumpdest, seems strange

padding is just adding zeroes to end of bytecode so I don't need to check length but just assume that there is stop at the end, evmone does it, that should be fine. I am not sure why it is always by 2

`256` it `0xFE` is just differently marked, it is probably just noice nothing more. (There is recent EIP that dissabled bytecode that start with `0xFE`: https://eips.ethereum.org/EIPS/eip-3541)

Best way to debug this is to get traces, I am not sure how to do in sputnik, but for revm you can use this `Inspector` here: https://github.com/bluealloy/revm/blob/main/bins/revme/src/statetest/trace.rs it will printout all stuff needed.

**Comment by rakita** [comment]
btw, what version of revm are you using?

**Comment by gd-0** [comment]
> btw, what version of revm are you using?

I'm using: version = "2.1.0"

**Comment by gd-0** [comment]
@rakita We think we've fixed it with this PR: https://github.com/bluealloy/revm/pull/259

Does it make sense to you?

**Comment by rakita** [comment]
In sputnik if len is zero, memory expansion is not taken into account: 
https://github.com/rust-blockchain/evm/blob/0036e1eba39444460fdf2752947195d1f14928f7/gasometer/src/lib.rs#L696-L698

same with openethereum: https://github.com/openethereum/openethereum/blob/6c2d392d867b058ff867c4373e40850ca3f96969/crates/vm/evm/src/interpreter/gasometer.rs#L420-L423

and I am doing it in other places for different opcodes.

That is the bug, good find!

**Comment by rakita** [comment]
There are a few fails test, probably related to the order of operations, in essence do check for data overflow then check for len zero and memory overflow. But let me check that statement.

**Comment by gd-0** [comment]
Amazing! Has been a nightmare trying to track the bug down so glad that was it!

**Comment by rakita** [comment]
Finding this kind of bug is the devil's job, traces usually help a lot and even with them it is hard to pinpoint.

kudos!

**Comment by rakita** [comment]
revm: v2.2.0 published
