### ISSUE TITLE
refactor memory expansion and memory gas calculation 

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#260]
Currently, it is hard to navigate and requires some cleanup.

Additionally, while doing that, introduce the `effective_len` variable inside interpreter memory that would calculate gas usage but not allocate memory until needed (until it is set by other opcodes).

**Comment by literallymarvellous** [comment]
Hi, I'd like to take on this issue.

**Comment by rakita** [comment]
Abandoning this idea
