### ISSUE TITLE
with-serde feature broken by move to ruint?

### ISSUE THREAD

**Issue by Owen66** [bluealloy/revm#266]
Hi,

When I try to compile using the latest version of revm with the `with-serde` feature enabled I get the following error. 
```the trait `Deserialize<'_>` is not implemented for `ruint::Uint<256, 4```

**Comment by Owen66** [comment]
This doesn't happen if I use `revm = "2.2.0"` in my cargo.toml file. But if I check it out from source and add the path in locally it breaks? Which branch/tag is 2.2.0 based on?

**Comment by rakita** [comment]
[it is in branch/](https://github.com/bluealloy/revm/blob/main/CHANGELOG.md#v17-tag)
I didnt want to include ruint as it is big release and with consensus bug I wanted other people to have easier transition.

feature for ruint/serde needs to be enabled on main

**Comment by Owen66** [comment]
Ah OK cool. Thanks!
