### ISSUE TITLE
TransactOut always returns empty Bytes

### ISSUE THREAD

**Issue by ufoscout** [bluealloy/revm#269]
It seems that no matter what we pass as input, the `TransactOut::Call(...)` or `TransactOut::Create(...)` of the `Executionresult` always contain empty Bytes after a `transact_commit()` call.
Is this expected? Is there a feature or option to enable it to return the desired data?

**Comment by rakita** [comment]
It is not used in any client, but some contracts can return output, that is basically `TransactionOut::Call`. For TransactionOut::Crate it returns created address and output (hm I will check this later to be sure)
