### ISSUE TITLE
How to add a custom precompile contract

### ISSUE THREAD

**Issue by KaoImin** [bluealloy/revm#280]
It seems that it is impossible to add a custom precompile when transact

**Comment by rakita** [comment]
You can create your own EVMImpl and add your set of precompiles:
Here it is how it is done inside  revm.

https://github.com/bluealloy/revm/blob/98baddd8c06f15cee281640c220df223dbf566f1/crates/revm/src/evm.rs#L143-L148

**Comment by gakonst** [comment]
should we write the Avax, Arbitrum, Celo and Binance precompiles, and expose them behind a feature flag?

**Comment by 0xarthurxyz** [comment]
As suggested by @gakonst, I'm moving the conversation re "Celo x Foundry" integration from here:
- https://github.com/foundry-rs/foundry/issues/1078#issuecomment-1344958839 
to this Github issue.

@gakonst had a question which I'm copying here for future reference:
>Most of these precompiles are stateful, so would like to understand how you are thinking about introducing that state, e.g. https://github.com/bluealloy/revm/blob/main/crates/revm_precompiles/src/lib.rs#L58

@palango (from Celo blockchain team) will be the best placed to answer this and other integration questions.

**Comment by palango** [comment]
To follow-up, I'm happy to help with the implementation of Celo-specific precompiles, but some general guidelines on how to handle stateful precompiles would help me a lot.

**Comment by rakita** [comment]
There was a idea to have `CustomPrecompiles` that would take EVM state and allow any kind of modification as the interpreter has.

It was here: https://github.com/bluealloy/revm/blob/2cb991091d32330cfe085320891737186947ce5a/crates/revm_precompiles/src/lib.rs#L58-L59

But I feel this approach is lacking and `CustomPrecompile` need to be specified inside `revm` crate and not inside `revm_precompiles` as dependency on revm internals is only possible in that way.

The stateful thing can be done through `Database`, as `CustomPrecompile` should take something similar (or same) as Inspector is doing here: https://github.com/bluealloy/revm/blob/2cb991091d32330cfe085320891737186947ce5a/crates/revm/src/inspector.rs#L67-L72

If you restructure that, this would be half job done.

**Comment by gakonst** [comment]
Here's a tutorial from Avalanche which may/may not be useful: https://docs.avax.network/subnets/hello-world-precompile-tutorial#stateful-precompiled-contracts: https://github.com/ava-labs/subnet-evm/blob/HelloWorldOfficialTutorial/precompile/contract.go#L64-L67

**Comment by palango** [comment]
> But I feel this approach is lacking and `CustomPrecompile` need to be specified inside `revm` crate and not inside `revm_precompiles` as dependency on revm internals is only possible in that way.

I guess as part of this also `Precompile` and its members should be moved over to the `revm` crate?

**Comment by rakita** [comment]
> > But I feel this approach is lacking and `CustomPrecompile` need to be specified inside `revm` crate and not inside `revm_precompiles` as dependency on revm internals is only possible in that way.
> 
> I guess as part of this also `Precompile` and its members should be moved over to the `revm` crate?

`Precompile` will be moved to `revm-primitives`, I started to spliting the project (`revm-interpreter` is now standalone) to allow more flexibility and new use cases for revm to be used. 
Will probably make it over the weekend.

**Comment by andy-thomason** [comment]
I'm judging from this conversation that user precompiles ar on the list of things to do.

At the moment we need to clone EVMImpl or implement them through an inspector as Anvil does.

Is there a move afoot to make EVMImpl less monolithic? It would be lovely to be able to implement Host
without the entirety of EVMImpl :grin:

**Comment by rakita** [comment]
> I'm judging from this conversation that user precompiles are on the list of things to do.
> 
> At the moment we need to clone EVMImpl or implement them through an inspector as Anvil does.
> 
> Is there a move afoot to make EVMImpl less monolithic? It would be lovely to be able to implement Host without the entirety of EVMImpl grin

As of recently, if you want to implement just a host, you can do it as `revm-interpreter` is standalone lib: https://github.com/bluealloy/revm/tree/main/crates 

so `revm-precompile` and `revm` are now dependent on `revm-primitives` this allows creation of new precompiles outside of revm project.

**Comment by palango** [comment]
In Celo we have some stateful precompile, i.e. precompiles that need read/write access to the state db. From the available precompile types it seems that this is currently not possible, as the db is not accessible from the `Env`. Is there a way or a plan to support that use-case?

https://github.com/bluealloy/revm/blob/00138a516c9705c31588aaccccd3dd28ad1cab75/crates/primitives/src/precompile.rs#L10-L11

**Comment by rakita** [comment]
> In Celo we have some stateful precompile, i.e. precompiles that need read/write access to the state db. From the available precompile types it seems that this is currently not possible, as the db is not accessible from the `Env`. Is there a way or a plan to support that use-case?
> 
> https://github.com/bluealloy/revm/blob/00138a516c9705c31588aaccccd3dd28ad1cab75/crates/primitives/src/precompile.rs#L10-L11

Needs to be added here https://github.com/bluealloy/revm/issues/798
It should be simple just adding additional enum
