### ISSUE TITLE
How to generate FFI C-Bindings for `revm` to be consumed within GoLang

### ISSUE THREAD

**Issue by cdc-Hitesh** [bluealloy/revm#292]
I am trying to replace the Golang EVM interpreter with `revm` for which I need to generate C-bindings for `revm` which can ultimately be called from the Go code.

Can someone assist in generating the correct FFI Golang or C Bindings for `revm` ?

**Comment by rakita** [comment]
[This](https://github.com/bluealloy/revm/tree/main/crates/revmjs/src) can maybe help you. It is binding for json->revm using `wasm_bindgen` I would try to use https://github.com/dtolnay/cargo-expand to expand `bindgen` output and see how it binds it, it is worth the shot.

**Comment by gakonst** [comment]
Here's an example of how we did it for Celo a few years ago:
* https://github.com/celo-org/celo-bls-go Go bindings
* https://github.com/celo-org/celo-threshold-bls-rs/tree/master/crates/threshold-bls-ffi/src how to write the FFI to CGo

**Comment by cdc-Hitesh** [comment]
> bindgen
Which means will need to manually write public C API in the rust code to generate FFI.

**Comment by cdc-Hitesh** [comment]
> [This](https://github.com/bluealloy/revm/tree/main/crates/revmjs/src) can maybe help you. It is binding for json->revm using `wasm_bindgen` I would try to use https://github.com/dtolnay/cargo-expand to expand `bindgen` output and see how it binds it, it is worth the shot.

I tried to run `cargo expand` then used `cbindgen` to generate C bindings from `revmjs/../lib.rs` but still don't see methods generated in the `cbindgen` output.

cc @rakita

**Comment by gakonst** [comment]
You need to do it manually, it's a bit rough 😅 pls see how I did it above

**Comment by cdc-Hitesh** [comment]
> You need to do it manually, it's a bit rough 😅 pls see how I did it above

I successfully created an FFI for EVM and used it in Golang.

My next struggle is replicating a Geth client StateDB into `revm` statedb.

Do you got any guide or thoughts for me @gakonst ?

**Comment by gakonst** [comment]
> My next struggle is replicating a Geth client StateDB into revm statedb.

Sorry not sure exactly there! Got the Go bindings anywhere we can peek?

**Comment by rakita** [comment]
Closing this as it is uncertain when or if this is going to be done inside revm
