### ISSUE TITLE
Make `revm-primitives`

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#304]
Multiple people told me that there is a need to import some types from revm so that their libraries can reuse them, impl `From` for casting, but not include the whole dependencies that revm has. So introducing `revm-primitives` seems like a logical step and re-export them inside revm so that we don't break current libs.  Additionally, this crate will be needed for `revm-interpreter` that is coming.

**Comment by gakonst** [comment]
@joshieDo is on this!

**Comment by rakita** [comment]
merged here: https://github.com/bluealloy/revm/pull/334
