### ISSUE TITLE
Support network "Shanghai"

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#315]
https://github.com/paradigmxyz/reth/actions/runs/3830942008/jobs/6519442884

introduced here https://github.com/ethereum/tests/commit/b63ca72ce9b4fc9f4c7dcb6636394ab1bc6ad9c1

I'm a bit confused by the 

> unknown variant `Shanghai`, expected one of `Frontier`, `FrontierToHomesteadAt5`, `Homestead`, `HomesteadToDaoAt5`, `HomesteadToEIP150At5`, `EIP150`, `EIP158`, `EIP158ToByzantiumAt5`, `Byzantium`, `ByzantiumToConstantinopleAt5`, `ByzantiumToConstantinopleFixAt5`, `Constantinople`, `ConstantinopleFix`, `Istanbul`, `Berlin`, `Berl

for `"network": "Shangai"`, it seems like this is `SpecName` but I could identify where the `network: SpecName` pair is parsed

ah looks like there is additional setup in reth https://github.com/paradigmxyz/reth/pull/700

**Comment by rakita** [comment]
Handled by `Other` serde flag: https://github.com/bluealloy/revm/blob/a05fb262d87c78ee52d400e6c0f4708d4c527f32/bins/revme/src/statetest/models/spec.rs#L30-L31
