### ISSUE TITLE
Inspector does not return `gas.limit()` as cost when an invalid opcode is detected

### ISSUE THREAD

**Issue by Wodann** [bluealloy/revm#335]
In Rethnet we implemented stack traces by using the `Inspector` trait. When comparing results against ethereumjs, we noticed that `revm` does not report the `Gas::limit()` in `Gas::spend()` when an invalid opcode is detected, whereas ethereumjs does (see [discussion](https://github.com/NomicFoundation/hardhat/pull/3593#discussion_r1080791076) or [`Inspector` trait implementation](https://github.com/NomicFoundation/hardhat/pull/3593/files#diff-4c5e3f43ac374461ee4d7d668e16bc3d6f5dfda3d4924b10439a56ba76af104eR491)).

I don't recall off the top of my head whether we return the gas limit for other exceptional halts, but it raises the question whether `revm` should be going this too?

**Comment by rakita** [comment]
I see, `call_end` is the problem, in revm if any halt happens I am ignoring gas and reading only `Return`, the proper way would be for revm to max out spend gas. I will check it a little bit latter, but the change should be small.

**Comment by Wodann** [comment]
Awesome; thanks!
