### ISSUE TITLE
Help with exports

### ISSUE THREAD

**Issue by andy-thomason** [bluealloy/revm#344]
Excellent work folks.

Currently the only exports from `journaled_state` are JournalEntry and JournaledState.

https://github.com/bluealloy/revm/blob/main/crates/revm/src/lib.rs#L18

It would be useful to have Map and State and Storage as these are used as outputs to transact()
and will avoid a duplicate dependency on hashbrown.

**Comment by rakita** [comment]
Hi Andy,

This deserves a little bit of cleanup. The best case would be to have hashbrown hashmap in one place inside `revm-primitives` and export them everywhere. And move away from `Map` alias to `HashMp`, just map is not intuitive what it is.

If you want to unblock yourself just expose the Map and it will get merged.

**Comment by andy-thomason** [comment]
Ok. Good to start somewhere :wink:

**Comment by andy-thomason** [comment]
It does look like `primitives` is the best place to expose this.

We already have `Account` and `StorageSlot` so only the `HashMap` is needed.

**Comment by rakita** [comment]
some imports cleanup done here; https://github.com/bluealloy/revm/pull/348
