### ISSUE TITLE
Add EIP-6049 for Shanghai support

### ISSUE THREAD

**Issue by gakonst** [bluealloy/revm#373]
[EIP-6049: Deprecate SELFDESTRUCT](https://eips.ethereum.org/EIPS/eip-6049)

This might be as simple as just adding a deprecated warning on the EVM when Shanghai is activated in an EVM instance?

**Comment by rakita** [comment]
Hey, we already talked about this, but it feels very strange when you are commenting like this after you said you would DM me changes
