### ISSUE TITLE
Question: Should `transact_commit` commit if ExecutionResult is not Success?

### ISSUE THREAD

**Issue by ufoscout** [bluealloy/revm#441]
Here is the current definition of the `transact_commit` fn:

```rust
    /// Execute transaction and apply result to database
    pub fn transact_commit(&mut self) -> Result<ExecutionResult, EVMError<DB::Error>> {
        let ResultAndState { result, state } = self.transact()?;
        self.db.as_mut().unwrap().commit(state);
        Ok(result)
    }
```

The way it is implemented, it calls `commit(state)` even if the result is different from `ExecutionResult::Success`.
Is it expected? Shouldn't it commit only on success?

**Comment by rakita** [comment]
It should commit, as it is a valid transaction and at least it updates the balance of the sender and benefactor/coinbase.
