### ISSUE TITLE
Port fondry/reth Inspectors to revm

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#462]
Both foundry and reth are using set of inspectors.

We should probably port them inside revm so they can be found in one place.

Inspector should be put here: https://github.com/bluealloy/revm/tree/main/crates/revm/src/inspector

Here are reth inspectors: https://github.com/paradigmxyz/reth/tree/main/crates/revm/revm-inspectors

**Comment by quangkeu95** [comment]
Is it resolved? I'm trying to start working on some good first issues.

**Comment by rakita** [comment]
> Is it resolved? I'm trying to start working on some good first issues.

It is not, go for it!

**Comment by mw2000** [comment]
@rakita is this resolved? If not I can try taking a stab at it.

**Comment by rakita** [comment]
@mw2000 it is not.

@mattsse what are inspectors that are reused and would benefit if they are found inside revm?

**Comment by mattsse** [comment]
we can close this, foundry should use revm-reth-inspectors

**Comment by rakita** [comment]
> we can close this, foundry should use revm-reth-inspectors

So the idea is to integrate Inspectors outside inside reth, we can go with that.

Would require only eip3155 tracer to be inside revm as it is needed for fuzzing. It is already nearly finished here: https://github.com/bluealloy/revm/blob/main/crates/revm/src/inspector/tracer_eip3155.rs

Will close this as eip3155 is tracked here: https://github.com/bluealloy/revm/issues/308
