### ISSUE TITLE
Option to increase or remove stack limit to support coverage computation in foundry

### ISSUE THREAD

**Issue by jat9292** [bluealloy/revm#469]
Hello, nowadays it is impossible to compute coverage using foundry for many realistic big contrats, because of a stack too deep error, see [foundry-rs#3357](https://github.com/foundry-rs/foundry/issues/3357) - in summary optimization is deactivated during compilation to be able to compute coverage from sourcemap.
My proposition would be to add an option to release or increase the default stack limit set to 1024 as per yellow paper, this would be a quick fix to compute coverage in any useful cases. 
I am not sure how to implement this, as a Rust beginner. I see that it is defined at least in two different places : [stack](https://github.com/bluealloy/revm/blob/e2f4d32650608dfd9d4378405339ac250aa8c007/crates/interpreter/src/interpreter/stack.rs#L4) and [interpreter](https://github.com/bluealloy/revm/blob/f91d5f910bb1f7ae2294c13217f800b49f0ded59/crates/interpreter/src/interpreter.rs#L18). I guess it would also make sense to increase the limit of the call stack, because it could also be likely be impacted by optimization.
What do you think about this proposal?

**Comment by rakita** [comment]
Just saw this, apologise for the late response.

It is fine with me, if you are up to it, you can follow how other `options_` are added (for example `optional_balance_check`) and just replace values.

And remove the constant from `stack.rs` it is leftover from refactoring.

**Comment by valo** [comment]
@jat9292 I believe this is an issue in the solidity compiler, not in revm. This seems to be relevant issue https://github.com/ethereum/solidity/issues/11638

I managed to reproduce the error by running `forge coverage` on the connext monorepo (https://github.com/connext/monorepo) and it blows up exactly on the compilation step.

I think this issue should be closed.
