### ISSUE TITLE
Support cfg for max init code size

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#490]
similar to 

https://github.com/bluealloy/revm/blob/e0ec1cc93228508f6eafba2cba5e08f64c0c5454/crates/primitives/src/env.rs#L91

could be an `Option` for setting the max limit or a feature gated bool to disable the check.

we need this for deploying foundry test contracts where we don't care about any code size.

**Comment by 0xJepsen** [comment]
Can you do something kinda like this?
https://github.com/primitivefinance/arbiter/blob/e58e39d116f0bfb577453f525d09cedb59494616/lib/simulate/src/environment/sim_environment.rs#L27

**Comment by mattsse** [comment]
this is now actually resolved via #503
