### ISSUE TITLE
no-std compilation breaks if target actually doesn't have std

### ISSUE THREAD

**Issue by lvella** [bluealloy/revm#493]
Tried to build with all features disabled (`"std"` among them) for target `riscv32imc-unknown-none-elf`, which actually doesn't have `std`, and compilation fails in many libraries that does require `std`.

I may be missing something, but I don't think there is a point in having a library supporting `#![no-std]` if their mandatory dependencies are only available on `std`-enabled targets, so I guess this is a bug?

**Comment by rakita** [comment]
tried it and it does fail.

All libs have `no_std` but for some reason the compiler does include core traits by default.

Do you have maybe solution for this?

**Comment by rakita** [comment]
ruint does not have support for `no_std`, it is being worked on to support it.

**Comment by lvella** [comment]
I have spent some time trying to track down the origin of `std` dependency, and the following command was helpful:
```
cargo tree --target=riscv32imc-unknown-none-elf -e features,normal
```
It seems the libraries with `std` feature enabled were included by the dependency paths:
- `revm-interpreter`→`revm-primitives`→`ruint`→...
- `revm-precompile`→`once_cell`

Unfortunately this analysis relied on crates having an `std` feature. It sounds simple enough, but I couldn't find a command/tool to follow the dependency tree and actually tell if each library was built with `#![no-std]` or not.

**Comment by rakita** [comment]
> It seems that `ruint` does have no-std support now.

Here is transition to `alloy` that uses newest ruint lib: https://github.com/bluealloy/revm/pull/617

**Comment by rakita** [comment]
fixed
