### ISSUE TITLE
How to set tx.origin while execute transaction

### ISSUE THREAD

**Issue by Lee-TC** [bluealloy/revm#510]
I want to simulate a call between contract. Firstly, I disable eip3607, which revert call when caller is contract.
Secondly, I change `caller` to `origin`.
```rust
Env {
        cfg: CfgEnv{
           disable_eip3607: true,
           ..Default::default()
        },
        block: fork_opts.env.block,
        tx: TxEnv{
            caller: origin.into(),
            ..Default::default()
        }
    }
```
However, revm will overwrite item `caller` to `from`, which is the contract address(msg.sender).
Is there some way to set tx.orgin while execute transaction?

**Comment by rakita** [comment]
wdym, revm doesn't overwrite values from ENV?

`caller`,`from`,`sender` are names for same thing, it recovered signer of signature of transaction.

Maybe it is related to subcalls where call context can be changed, more on it here: https://ethereum.stackexchange.com/questions/3667/difference-between-call-callcode-and-delegatecall

**Comment by Lee-TC** [comment]
I know that `caller`, 'from', 'sender' are same thing. I just want to simulate a call between contracts:
```
                   sign tx                    call      
A(tx.origin, EOA) -------> B(msg.sender, CA) ------> C(CA)
 
```
I want to simulate B -> C use revm, However `tx.origin` will be set as B, Is there some way to set tx.origin to A? Thanks.

**Comment by rakita** [comment]
If this is sub call, you can hook up the `Inspector` and change values of `CallInputs` https://github.com/bluealloy/revm/blob/main/crates/revm/src/inspector.rs#L82

**Comment by Lee-TC** [comment]
Okay, find `tx.origin` op's implementation  in `host_env.rs`
```rust
pub fn origin(interpreter: &mut Interpreter, host: &mut dyn Host) {
    gas!(interpreter, gas::BASE);
    push_b256!(interpreter, host.env().tx.caller.into());
}
```
and `msg.sender` op's implementation in `system.rs`
```rust
pub fn caller(interpreter: &mut Interpreter, _host: &mut dyn Host) {
    gas!(interpreter, gas::BASE);
    push_b256!(interpreter, B256::from(interpreter.contract.caller));
}
```
So I just need change host_env's `caller` or interpreter's `caller`, thanks 😊
