### ISSUE TITLE
EIP-6780: SELFDESTRUCT only in same transaction

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#524]
More info here: https://eips.ethereum.org/EIPS/eip-6780

**Comment by rakita** [comment]
Add it after account state: https://github.com/bluealloy/revm/pull/499

**Comment by chirag-bgh** [comment]
Hey @rakita, can I take this?

**Comment by lorenzofero** [comment]
Hi! I tried to take a look at this EIP and issue. I was wondering if I could try to tackle it or if it 'reserved' (sorry for the lack of a better term) to the more experienced/main contributors of this project. If this is the case it's fine I have no problems with it and I understand.

I'd be happy to work at it with some support here and there, since it is my first EIP I'll try to do. Thanks a lot!

**Comment by rakita** [comment]
> Hi! I tried to take a look at this EIP and issue. I was wondering if I could try to tackle it or if it is 'reserved' (sorry for the lack of a better term) to the more experienced/main contributors of this project. If this is the case it's fine I have no problems with it and I understand.
> 
> I'd be happy to work at it with some support here and there, since it is my first EIP I'll try to do. Thanks a lot!

You can try it, this should be a small change. There is already a crated flag inside the `Journal` that should help with this.

**Comment by lorenzofero** [comment]
Where can I find the appropriate tests for this EIP? Looking at https://github.com/ethereum/tests I've found something here https://github.com/ethereum/tests/tree/develop/EIPTests/Pyspecs/cancun, however they fail to run with this error: ```Error: Statetest(SerdeDeserialize(Error("missing field `env`", line: 165, column: 5)))```
I don't understand if I should fix something here or if the tests inside such folder are not really compatible with the existing revm code. Thanks for the support!

**Comment by rakita** [comment]
> Where can I find the appropriate tests for this EIP? Looking at https://github.com/ethereum/tests I've found something here https://github.com/ethereum/tests/tree/develop/EIPTests/Pyspecs/cancun, however they fail to run with this error: `` Error: Statetest(SerdeDeserialize(Error("missing field `env`", line: 165, column: 5))) `` I don't understand if I should fix something here or if the tests inside such folder are not really compatible with the existing revm code. Thanks for the support!

Not that I know for state tests, they are probably going to be added afterwards. Those jsons are blockchain tests that can be run inside reth: https://github.com/paradigmxyz/reth/tree/main/testing/ef-tests, it seems the usage explanation is here: https://github.com/paradigmxyz/reth/pull/2847

Can you push the PR so I can check it out?
