### ISSUE TITLE
EIP-4788: Beacon block root in the EVM

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#525]
Add new stateful precompile that saved beaconroot

Root should be set before executing transaction.

Precompile should have access to the state.

More info here: https://eips.ethereum.org/EIPS/eip-4788

**Comment by 0xJepsen** [comment]
I am down to take a crack at this if the 4844 looks good to you!

**Comment by rakita** [comment]
> I am down to take a crack at this if the 4844 looks good to you!

Hey, eip4844 pr doesn't look great, I still need to look at it in detail but I lean on just rewriting it as it seems easier, in mcopy case when I look at it now, that would be a better choice. 

For this EIP, eth devs decided to do it in a different way, as in having a system bytecode that is going to be called at the start of the block. You can read about it inside `Eth R&D` discord `testing` chat

**Comment by 0xJepsen** [comment]
If you have feedback it would be really helpful for me to learn on how and what you would like to be done better. I spent a lot of time studying and working on it trying to do it correctly.

**Comment by 0xJepsen** [comment]
> > I am down to take a crack at this if the 4844 looks good to you!
> 
> Hey, eip4844 pr doesn't look great, I still need to look at it in detail but I lean on just rewriting it as it seems easier, in mcopy case when I look at it now, that would be a better choice.
> 
> For this EIP, eth devs decided to do it in a different way, as in having a system bytecode that is going to be called at the start of the block. You can read about it inside `Eth R&D` discord `testing` chat

If you have feedback on 4844, it would be really helpful for me to learn what you would like to be done better, and how to do it. I spent a lot of time studying and working on this, trying to do it correctly. I don't expect it to be perfect right now, but with good feedback I will do it correctly. It is important to me to understand what is not good / incorrect about the current implementation so that i know how to do better.

**Comment by rakita** [comment]
> > > I am down to take a crack at this if the 4844 looks good to you!
> > 
> > 
> > Hey, eip4844 pr doesn't look great, I still need to look at it in detail but I lean on just rewriting it as it seems easier, in mcopy case when I look at it now, that would be a better choice.
> > For this EIP, eth devs decided to do it in a different way, as in having a system bytecode that is going to be called at the start of the block. You can read about it inside `Eth R&D` discord `testing` chat
> 
> If you have feedback on 4844, it would be really helpful for me to learn what you would like to be done better, and how to do it. I spent a lot of time studying and working on this, trying to do it correctly. I don't expect it to be perfect right now, but with good feedback I will do it correctly. It is important to me to understand what is not good / incorrect about the current implementation so that i know how to do better.

Gave feedback as it should be good to learn from it, I still intend to rewrite it as in the end I will be left with maintaining it.

**Comment by 0xJepsen** [comment]
Revm is a very important part of the project i work on and the greater ethereum ecosystem. I intend to help where i can to support the project which is why i am here contributing and learning in the first place.

**Comment by rakita** [comment]
@Rjected just to confirm, there is no need to have any changes inside revm for this?

**Comment by Rjected** [comment]
> @Rjected just to confirm, there is no need to have any changes inside revm for this?

yes, PR is on reth here and does not require EVM changes (see how the block / tx env is set):
https://github.com/paradigmxyz/reth/pull/4457

**Comment by gakonst** [comment]
Given that, should we close this?

**Comment by rakita** [comment]
No actions needed
