### ISSUE TITLE
EIP-4844: Shard Blob Transactions

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#526]
There are three things related to evm.

* `BLOBHASH` (with opcode 0x49) which reads index from the top of the stack as big-endian uint256, and replaces it on the stack with `env.tx.blob_versioned_hashes[index]`
* And precompile that needs to be added at `POINT_EVALUATION_PRECOMPILE_ADDRESS` that verifies a KZG proof which claims that a blob (represented by a commitment) evaluates to a given value at a given point.
* Data gas accounting.

More info here: https://eips.ethereum.org/EIPS/eip-4844

**Comment by 0xJepsen** [comment]
After familiarizing myself with this part of the stack in #528 I'd be interested to take a stab at this. Been reviewing the docs and feel like i have a decent intuition on how to approach this.

**Comment by rakita** [comment]
> After familiarizing myself with this part of the stack in #528 I'd be interested to take a stab at this. Been reviewing the docs and feel like i have a decent intuition on how to approach this.

for MCOPY I already knew exactly how it need to look and it was very easy to add so I could guide you line by line as I did it, and you have seen how sensitive this is as even with it you made multiple consensus errors, with this, I am not that sure, so until this comes next in my work I would be blank. If you are okay with that, go for it!
