### ISSUE TITLE
Ethereum hardfork: Cancun

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#527]
List of EIP for Cancun upgrade:
- [x] #524 
- [x] #523 
- [x] #526 
- [x] #525 
- [x] #154 

[Execution spec](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/cancun.md#included-eips)

**Comment by rakita** [comment]
@Evalir  regarding this q: https://github.com/foundry-rs/foundry/issues/5574#issuecomment-1672686215

ETA depends on Ethereum core devs and when they finalise Cancun, for example, EIP-4788 got a major change last week.

I decided to drop https://github.com/bluealloy/revm/pull/536 PR as i need to be mindful of my time and it is safer to just rewrite it, as I got burned with mcopy that took a lot of my time, in the end, there were multiple consensus issues found after it was merged https://github.com/bluealloy/revm/pull/528, if you want you can take a stab at it on rewriting it, be free to do it. 

Others EIP I would not recommend,as beaconroot is not finished and selfdestruct requires a lot of local knowledge.

**Comment by Evalir** [comment]
@rakita makes sense—thanks for the update!

I think I might leave 4844 up to you—it's true that it's quite sensitive to get right as a bug here affects reth upstream, and I'm not as familiar with the EIP as a whole, nor any upstream assumptions we might have from reth.

For now foundry is on latest main and unblocked the sol team, so it should be good for now for 1153 👍

**Comment by DaniPopes** [comment]
This can be closed @rakita

**Comment by rakita** [comment]
Implemented
