### ISSUE TITLE
Calling Contract from Contract

### ISSUE THREAD

**Issue by zombie-einstein** [bluealloy/revm#534]
Are there any known issues or requirements to call contracts from contracts?  I have a contract that calls another deployed simple ERC20 contract to mint tokens:

```
// ERC20 Contract sol
...
  function mint(address account, uint256 value) public virtual onlyOwner returns (bool) {
      _mint(account, value);
      return true;
  }

// Calling Conract sol
...
  function mint(
      address token,
      address to,
      uint256 amount
  ) external override onlyOwnerIfPermissioned returns (uint256) {
    require(!_nonMintable[token], 'Error: not mintable');
    require(
      amount <= MAX_MINT_AMOUNT * (10 ** ERC20(token).decimals()),
      'Error: Mint limit transaction exceeded'
    );
    ERC20(token).mint(to, amount);
    return amount;
  }
```

Calling the `mint` function on the second contract always reverts the transaction with an empty response/reason. As far as I can see the call should work:

- The same contracts deployed on hardhat works
- I can successfully call functions each contract individually (obviously except for the function that calls another contract) including the mint function on the ERC20 contract.
- I disabled `eip3607` in the environment cfg

Is there some step or setting I am missing?

**Comment by 0xJepsen** [comment]
Could you describe how you deployed the two contracts?

**Comment by zombie-einstein** [comment]
Actually found the issue! Thanks for looking anyway.

**Comment by zombie-einstein** [comment]
Actually found the issue! Thanks for looking anyway.

**Comment by michcio1234** [comment]
@zombie-einstein Would you mind sharing what was your problem?

**Comment by zombie-einstein** [comment]
Sure (sorry for slow reply) I'd just made a dumb mistake casting between revm and ethers-core Address types, so the contract addresses that were being called from the first contract were incorrect.
