### ISSUE TITLE
Rename `DatabaseRef` trait function to `*_ref`

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#540]
this is very easy to mess up:

https://github.com/paradigmxyz/reth/pull/3589

for example when applying overrides on Cache

1. fetch via `Database::basic`
2. update account via `insert_account_info`
3. `Database::basic` still returns None because marked as NonExisting in the first step

perhaps this is even a bug and `insert_account_info` should update the state it as existing?

**Comment by rakita** [comment]
Will write it here, @mattsse pointed out (and I agree with it) that having the same named functions inside `Database` and `DatabaseRef` is confusing and can lead to unexpected outcomes. 

So breaking DatabaseRef and appending `_ref` should be a way forward for this. Just need to decide when to do it, probably after next release.

The `insert_account_info` functionality is really debatable, added out of necessity but had those kinds of footguns.

**Comment by mattsse** [comment]
> So breaking DatabaseRef and appending _ref should be a way forward for this. Just need to decide when to do it, probably after next release.

sg!

FYI @Evalir

**Comment by Evalir** [comment]
Yep agreed with everything here—I think breaking this interface will also help clarify what's the use of each trait. Happy to help with this, and will migrate foundry once we break the interface 👍

**Comment by silathdiir** [comment]
Hi, I'd like to fix this if no one is working on it (and it could be fixed in this release).
