### ISSUE TITLE
calc not public 

### ISSUE THREAD

**Issue by supernovahs** [bluealloy/revm#566]
https://github.com/bluealloy/revm/blob/main/crates/interpreter/src/gas/calc.rs

Can u make this file public ? 

Ref: 
https://github.com/paradigmxyz/reth/issues/3235

**Comment by BrazilRaw** [comment]
https://github.com/bluealloy/revm/pull/575

i opened a pr

**Comment by supernovahs** [comment]
thx

**Comment by BrazilRaw** [comment]
> thx

calc is now public
