### ISSUE TITLE
Test overflowed the stack

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#589]
It seem something got changed and default stack size is not enough for running eth tests, bumped it to 3MB does the job but should check to be sure

**Comment by valo** [comment]
Interesting... Let me check this. Should be possible to bisect the history and pinpoint the change.

**Comment by valo** [comment]
Something went wrong during the cleanup stage of #522 and the stack is blowing up in release mode in the final PR. The offending commit is this cleanup that I did https://github.com/valo/revm/commit/d2e5c17c94fa3f6ecfa9b080e2dc345a8bbf41f9 Seems like the `handle_` functions are actually impacting the stack size after all. I have no idea how this slipped through, as I remember running these tests dozens of times.

I'll see how I can fix this. May be re-introducing these handle functions has benefits.
