### ISSUE TITLE
Dont insert empty reverts in state

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#634]
Noticed here: https://github.com/bluealloy/revm/pull/626#discussion_r1301347468

We should check if revert is empty and not insert it.

**Comment by lorenzofero** [comment]
Hi! Sorry for the naive question: I tried to give a look at it to become more familiar with this part of the codebase; is it possible this is the solution to the issue? Or am I skipping some storage related operations to do depending on `AccountStatus`?

```diff
--- a/crates/revm/src/db/states/bundle_account.rs
+++ b/crates/revm/src/db/states/bundle_account.rs
@@ -151,7 +151,7 @@ impl BundleAccount {
         let info_revert = if self.info != updated_info {
             AccountInfoRevert::RevertTo(self.info.clone().unwrap_or_default())
         } else {
-            AccountInfoRevert::DoNothing
+            return None;
         };

         match updated_status {
```

**Comment by rakita** [comment]
> Hi! Sorry for the naive question: I tried to give a look at it to become more familiar with this part of the codebase; is it possible this is the solution to the issue? Or am I skipping some storage related operations to do depending on `AccountStatus`?
> 
> ```diff
> --- a/crates/revm/src/db/states/bundle_account.rs
> +++ b/crates/revm/src/db/states/bundle_account.rs
> @@ -151,7 +151,7 @@ impl BundleAccount {
>          let info_revert = if self.info != updated_info {
>              AccountInfoRevert::RevertTo(self.info.clone().unwrap_or_default())
>          } else {
> -            AccountInfoRevert::DoNothing
> +            return None;
>          };
> 
>          match updated_status {
> ```

Ah not exactly, maybe account info is not changed, but storage values could be, so revert for that should still be present.

It is a simple change to check but we need to check that both `AccountInfoRevert` is `DoNothing` **and** if `storage.is_empty()`. You probably need to refactor a few small things inside that fn and add `is_empty()` for `AccountRevert`.

**Comment by rakita** [comment]
> Thanks a lot for the suggestion! Let me know if now is ok

Left comments there, but that is the right direction!
