### ISSUE TITLE
Make BundleBuilder

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#644]
The current initialization of the bundle is with `new` function that takes two big iterators. This should be done a lot better with a builder that is going to output the bundle state.

https://github.com/bluealloy/revm/blob/0b9c12e6e9d876a93deaf718d0988e3f6c3c7031/crates/revm/src/db/states/bundle_state.rs#L58-L77

**Comment by darknight** [comment]
I'm reading the codebase and come across this issue, wondering if it's good to be first issue. If so, I'd like to take it.
And If I understand correctly, what is expected here is apply builder pattern to initialize `BundleState`, correct?

**Comment by rakita** [comment]
> @rakita Hi, I'm reading the codebase and come across this issue, wondering if it's good to be first issue. If so, I'd like to take it. And If I understand correctly, what is expected here is apply builder pattern to initialize `BundleState`, correct?

It is a good first issue, go for it!

**Comment by rakita** [comment]
closed https://github.com/bluealloy/revm/pull/649
