### ISSUE TITLE
bug: modexp gas check

### ISSUE THREAD

**Issue by lispc** [bluealloy/revm#665]
https://github.com/bluealloy/revm/blob/1053d0e50569a7e2f524297654b098fbfc5ba2c8/crates/precompile/src/modexp.rs#L83-L85

i think here if `base_len == 0 && mod_len == 0` we still need to check gas is larger than min_gas? or we need to return OutOfGas?

**Comment by rakita** [comment]
It would be good to do a check there, to be consistent. Check is additionally done when deducting gas and would return `OutOfGas` error here:
https://github.com/bluealloy/revm/blob/bef9edd6d2d8342ca4703965b50f607a7fb1b583/crates/revm/src/evm_impl.rs#L603-L615

Do you want to make a PR for this?
