### ISSUE TITLE
Introduce error type for EnvError 

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#685]
https://github.com/bluealloy/revm/blob/c0767fa3e3b49497fa67cef37a9519fa6e55dd12/crates/primitives/src/result.rs#L127-L128C22

After eip4844 we would have two filed that should have been set if spec is Cancun. We can group them as a cleanup.

Do it after eip4844 PR is merged: https://github.com/bluealloy/revm/pull/668

**Comment by hack3r-0m** [comment]
I would like to work on this, am i correct in understanding that EnvError will include `PrevrandaoNotSet` & `ExcessBlobGasNotSet` and would be would be variant of `EVMError` ?
