### ISSUE TITLE
Document and implement formatting for errors

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#740]
`InvalidTransaction`, `InvalidHeader` etc (`crates/primitives/src/result.rs`) do not implement `std::fmt::Display` or `std::error::Error`, which forces downstream crates to implement their own formatting/conversions (see [Foundry](https://github.com/foundry-rs/foundry/blob/adb526bc1db52db96ba6c69be178022f97e76ec5/crates/anvil/src/eth/error.rs#L203), [Reth](https://github.com/paradigmxyz/reth/blob/e83d3aa704f87825ca8cab6f593ab4d4adbf6792/crates/rpc/rpc/src/eth/error.rs#L371))

**Comment by rakita** [comment]
done
