### ISSUE TITLE
Fix `rustdoc` warnings

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#742]
Running `cargo doc --workspace --no-deps --all-features` generates a ton of `rustdoc` warnings, and more can be enabled with `#![warn(rustdoc::all)]`. These should be fixed and enforced with a CI job (see [Alloy](https://github.com/alloy-rs/core/blob/0c21fcc48eab0b52c20d3e98c739bac862aad8ff/.github/workflows/ci.yml#L71-L82)).

Additionally, we should also enable automatic feature detection in generated docs with the nightly `doc_auto_cfg` feature: [in Cargo.toml](https://github.com/alloy-rs/core/blob/0c21fcc48eab0b52c20d3e98c739bac862aad8ff/crates/primitives/Cargo.toml#L16-L18), [in lib.rs](https://github.com/alloy-rs/core/blob/0c21fcc48eab0b52c20d3e98c739bac862aad8ff/crates/primitives/src/lib.rs#L15)

**Comment by Sabnock01** [comment]
Would like to take this one.
