### ISSUE TITLE
REVM triggers Uniswap reentrancy guard

### ISSUE THREAD

**Issue by NianSol** [bluealloy/revm#761]
When trying to make Swap on uniswap using the method swapExactETHForTokensSupportingFeeOnTransferTokens it returns a REVERT UNISWAP V2: LOCKED

There's no loops in my code
Before the revert it stops at PC 19213, the revert being 19215
Some people reported the same error on Hardhat in 2020

`Ok(ResultAndState { result: Revert { gas_used: 85902, output: b"\x08\xc3y\xa0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0 \0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x11UniswapV2: LOCKED\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" }`

**Comment by rakita** [comment]
Not revm related as reentrency is purely a bytecode logic
