### ISSUE TITLE
Optimism execution

### ISSUE THREAD

**Issue by Wollac** [bluealloy/revm#781]
When I tried to use the Optimism execution behind the `optimism` feature flag of version `v3.5.0`, I ran into the following problems:
- `Handler::optimism()` is never used. So even if `env.cfg.optimism` is `true`, the Optimism specific fee handling is not applied.
- The _Base Fee Vault_ calculation in the Optimism handler uses the L1 base, but according to the [L2 Execution Engine spec](https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#base-fees-base-fee-vault), I was under the impression that `env.block.basefee * (gas.spend() - gas_refund)` should be used instead.
- When the `optimism` feature is enabled while  `env.cfg.optimism` is `false` for Ethereum transactions, the `tx_l1_cost` is still computed, which can lead to a panic as obviously the `enveloped_tx` is not provided in this case.

If the above observations are indeed correct and it would be helpful, I can provide a PR for these issues.

**Comment by refcell** [comment]
Thank you for reporting this! Will take a look, reproduce, and get back to you!

As a side note, if you make a PR, it would be preferable to split it up to make reviewing and adding the relevant unit tests easier.

**Comment by rakita** [comment]
@Wollac thank you!

`Handler::optimism()` should have been used if optimism flag is true here:
https://github.com/bluealloy/revm/blob/02d85ac751b79cd37d06627c1b5281a1d7f5b61d/crates/revm/src/evm_impl.rs#L418

For the future, the idea is to create the `RevmBuilder` that would allow setting either of the handler (Still need to flush some thing for it), but for now, just changing the code to `::optimism()` should do the work.

The Second point I will leave for @refcell, for the third point we definitely should not panic.

**Comment by refcell** [comment]
Left a couple of nits, but besides those, you're pr looks great! Really exciting that you were able to test this against Optimism Blocks!!

On the topic of unit tests, I think pushing those into other prs is totally reasonable.

**Comment by clabby** [comment]
Very exciting news that you guys are successfully executing Optimism blocks! Thanks a ton for fixing these up :)

**Comment by Wollac** [comment]
Fixed with #789
