### ISSUE TITLE
`fn contract` in `bundle_state.rs` should accept `AsRef`

### ISSUE THREAD

**Issue by alessandromazza98** [bluealloy/revm#782]
Related to https://github.com/paradigmxyz/reth/pull/4647

`contract` function in `BundleBuilder` should accept `AsRef<Bytecode>` so that in Reth it could be possible to directly use the function in this way:

```rust
bundle_builder.contract(address, bytecode);
```

and not being forced to do:
```rust
bundle_builder.contract(address, bytecode.0);
```

**Comment by rakita** [comment]
Seems strange so i will close it, I have recommend other path
