### ISSUE TITLE
Javascript ( Typescript ) bindings similar with solc-js?

### ISSUE THREAD

**Issue by ghost** [bluealloy/revm#79]
Would be great to have a javascript bindings for revm similar with [solc-js](https://github.com/ethereum/solc-js)

If it is available, it would be possible to run revm inside various testing tools & even on ide like remix.

**Comment by rakita** [comment]
https://github.com/bluealloy/revm/tree/main/crates/revmjs
https://www.npmjs.com/package/revmjs
I think i need to refresh it and update it with new revm version

**Comment by 0xAyanami** [comment]
@rakita Everything is rust down there and I could not see any js related files like package.json, is it normal?

**Comment by rakita** [comment]
@0xAyanami this is kinda a rust lib, but it can be compiled to wasm

**Comment by rakita** [comment]
No plan atm to fully support this.

**Comment by 0xTARC** [comment]
Theoretically you could still compile to WASM and run in the browser right?

Would you have to compile to WASI and then use a WASI shim in the browser? Or could you just execute solidity functions via WASM directly

High level, what would need to be done to execute evm bytecode in the browser with revm?

**Comment by rakita** [comment]
It is possible, revm is wasm complient with `no_std` and few projects use it. We even have no_std build in CI to test it.

So what is needed is a wrapper around revm lib that interacts with js/wasm-bindgen
