### ISSUE TITLE
Integrate revm in goevmlab fuzzer

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#791]
Integrate revm inside evm fuzzer found in goevmlab.

https://github.com/holiman/goevmlab/tree/master to enable fuzzing

We already have a `revme statetest` that calls the ethereum tests and there is probably a few modifications that needs to be done to support same output format for goevmlab.

**Comment by 1010adigupta** [comment]
I can take up this issue

**Comment by rakita** [comment]
> I can take up this issue

go for it!

**Comment by 0x0elliot** [comment]
if there is no progress made here, i can take this up :)

**Comment by rakita** [comment]
> if there is no progress made here, i can take this up :)

A few things are pending here: https://github.com/holiman/goevmlab/issues/113#issuecomment-1869548738 i wanted to finish EvmBuilder before I tackle that. If you want to go for it, do it on top of EvmBuilder branch

EvmBuilder is here: https://github.com/bluealloy/revm/pull/888 i am doing the last cleanup pass and writing documentation for it.

**Comment by 0x0elliot** [comment]
i actually do want to. it's just that i am not sure what to do and where to begin. some context on what to tackle would help!

**Comment by hack3r-0m** [comment]
I would like to work on this issue, i was following conversation at https://github.com/holiman/goevmlab/issues/113 and got revm working with testdata

after removing print logs & debug statements, making `_info` optional and adding empty `out` to `TestUnit`, i was able to produce some output: https://gist.github.com/hack3r-0m/90841af32e189611636c7f38498e3d56

have few questions regarding how to proceed:

- should this be new sub-command under revme or it should work as statetest with additional args?
- is there any convention on what goes to stdout and stderr? from goemvlab traces, it looks like all client follow different approaches
- revm traces have addtional `depth` field which other traces don't have in goevmlab, I am not sure on how to tackle that, should it log out stateRoot at each depth increment?

**Comment by rakita** [comment]
> I would like to work on this issue, i was following conversation at [holiman/goevmlab#113](https://github.com/holiman/goevmlab/issues/113) and got revm working with testdata
> 
> after removing print logs & debug statements, making `_info` optional and adding empty `out` to `TestUnit`, i was able to produce some output: https://gist.github.com/hack3r-0m/90841af32e189611636c7f38498e3d56
> 
> have few questions regarding how to proceed:
> 
> * should this be new sub-command under revme or it should work as statetest with additional args?
> * is there any convention on what goes to stdout and stderr? from goemvlab traces, it looks like all client follow different approaches

I started working on this, here is the branch: https://github.com/bluealloy/revm/tree/goevmlab it is close to finished

**Comment by rakita** [comment]
Done
