### ISSUE TITLE
Comment output of cachegrind in PR

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#797]
Not sure how to do this but would be very beneficial

As i am on mac valgrind does not work and i have a Docker file:
```
FROM alpine:latest
RUN apk add g++ gcc clang-dev valgrind curl git llvm

# Install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Add .cargo/bin to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Check cargo is visible
RUN cargo --help
```

Run docker with:
` docker run -it -v $PWD:/tmp -w /tmp valgrind:1.0`

And I run snailtracer to get results like this:
```
cargo b -r -p revm-test --bin snailtracer
valgrind --tool=cachegrind target/release/snailtracer
```

**Comment by 0x0elliot** [comment]
Can i help out with this issue? Seems simple enough as an entrypoint for someone who's new to the EVM ecosystem.

**Comment by rakita** [comment]
> Can i help out with this issue? Seems simple enough as an entrypoint for someone who's new to the EVM ecosystem.

Go for it, it is mostly github actions and how to output it in PR (not sure what github plugging are out there for it)

**Comment by 0x0elliot** [comment]
@rakita A bit confused as to what needs to be done. Do you mind giving me a bit of context? I reassure you, this would get lesser and lesser with the next few contributions.

If you wish, I can ping you somewhere else too (a discord server, the revm telegram group etc)

**Comment by rakita** [comment]
> @rakita A bit confused as to what needs to be done. Do you mind giving me a bit of context? I reassure you, this would get lesser and lesser with the next few contributions.
> 
> If you wish, I can ping you somewhere else too (a discord server, the revm telegram group etc)

Idea is to run valgrind cachegrind on every new PR.

cachegrind is used to deduce the number of executed instructions and is a good metric to check how fast/slow the program is. In comparison, time measurement can be variable and hard to get one value, while num of the instruction is always the same for the same program so it is a good ballpark.

So executing this on every PR means adding github action: https://github.com/bluealloy/revm/tree/main/.github/workflows and using some (i hope it exists)  github plugin that outputs this to the PR as a comment.

Hope that this makes it clearer.

**Comment by 0x0elliot** [comment]
Thanks! That does. Let me play around with this.

**Comment by rakita** [comment]
Still need to fix PAT and github token but issue is considered done
