### ISSUE TITLE
Allow precompiles to capture state 

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#798]
currently precompiles are limited to functions:

https://github.com/bluealloy/revm/blob/68f78ae0a4c2b351f2fe36236164d07933d0d4d5/crates/primitives/src/precompile.rs#L10-L11

it would be useful to allow them to capture state, by supporting `Arc< dyn Fn(&[u8], u64, env: &Env) -> PrecompileResult`

**Comment by rakita** [comment]
Would add another enum item for this, and before opening this should made this extendable with handlers refactor

**Comment by mattsse** [comment]
an enum would be the proper abstraction imo.

where the third variant is something like an `Arc<dyn PrecompileTrait>`

where precompile trait mirrors `fn(&[u8], u64, env: &Env) -> PrecompileResult`

perhaps we could also pass the evmdata as an additional parameter, in case a precompile needs access to the journalstate for some reason
