### ISSUE TITLE
refactor(interpreter): refactor `sstore_cost`

### ISSUE THREAD

**Issue by tcoratger** [bluealloy/revm#830]
## Description:
The `sstore_cost` function may need refactoring to improve code clarity: 
https://github.com/bluealloy/revm/blob/df44297bc3949dc9e0cec06594c62dd946708b2a/crates/interpreter/src/gas/calc.rs#L188-L238

The current implementation is complex with nested `if` conditions, making it difficult to understand and maintain. The purpose of this issue is to refactor the function to make it more elegant and improve code quality.

## Expected Benefits:
- Improved code readability and maintainability.
- Reduced complexity and enhanced documentation.
- Potential for better performance and reduced risk of bugs.

## Proposed solution
In my opinion we can act in two relatively simple ways firstly:
- It is possible to reduce the nesting of certain if conditions, this is a fairly simple refactoring but which already makes it possible to improve the readability, I think.
- It is possible to move the following statement at the beginning of the function in order to improve readability and avoid useless calculations once the condition is met with a direct `None` return:
```rust
// EIP-1706
if gas <= CALL_STIPEND {
    return None;
}
```

**Comment by mw2000** [comment]
I can work on this

**Comment by mw2000** [comment]
Made a Pr #891 that should fix this
