### ISSUE TITLE
Use a faster hash for the state diff map

### ISSUE THREAD

**Issue by onbjerg** [bluealloy/revm#87]
The default hasher is pretty slow for `HashMap`s. We should consider using something like https://docs.rs/seahash/latest/seahash/

**Comment by rakita** [comment]
Found this: 
https://gist.github.com/daboross/976978d8200caf86e02acb6805961195?permalink_comment_id=4205660#gistcomment-4205660

**Comment by shekhirin** [comment]
@rakita yep, it seems faster than seahash according to that benchmark which also has several even better candidates https://github.com/rurban/smhasher

both are non-cryptographic and should be ok for some of the revm usecases

**Comment by rakita** [comment]
> @rakita yep, it seems faster than seahash according to that benchmark which also has several even better candidates https://github.com/rurban/smhasher
> 
> both are non-cryptographic and should be ok for some of the revm usecases

Should be okaу for all revm usecases, it is just i didnt spend time changing it 😅

Good link, thank you for sharing

**Comment by shekhirin** [comment]
TIL that `hashbrown` already uses `ahash` by default, and `revm` uses `hashbrown` for all performance-critical things 🙂 
```rust
/// Default hasher for `HashMap`.
#[cfg(feature = "ahash")]
pub type DefaultHashBuilder = ahash::RandomState;
```
source: https://github.com/rust-lang/hashbrown/blob/1d2c1a81d1b53285decbd64410a21a90112613d7/src/map.rs#L11-L13

**Comment by rakita** [comment]
hashbrown it is :)
