### ISSUE TITLE
Suggesting specifc Create Inspector return type for `call` `call_end`

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#873]
While it is possible and perhaps desired to override the address:

https://github.com/bluealloy/revm/blob/3608d2d893f973c9b86b6db60b3ffa11a61ef17c/crates/revm/src/inspector.rs#L134-L134

most of the time it is not needed.

Since we already made changes to the Inspector, I'm suggesting to make this return type a bit easier as well like

`struct CreateOutcome {result: InterpreterResult, address: Option<Address>}`

and some helper functions like `CreateOutcome::continue() -> Self`

what's the difference between the Option here:

https://github.com/bluealloy/revm/blob/3608d2d893f973c9b86b6db60b3ffa11a61ef17c/crates/revm/src/inspector.rs#L114-L118

and non optional here:

https://github.com/bluealloy/revm/blob/3608d2d893f973c9b86b6db60b3ffa11a61ef17c/crates/revm/src/inspector.rs#L129-L134

**Comment by loocapro** [comment]
May I take this?

**Comment by rakita** [comment]
Can you do it on top of the [external_field](https://github.com/bluealloy/revm/tree/external_field) branch? There are a few conflicting changes there

**Comment by loocapro** [comment]
Sure!

**Comment by mahmudsudo** [comment]
has this been taken already

**Comment by loocapro** [comment]
> has this been taken already
> 
> 

Yes sorry.

**Comment by loocapro** [comment]
HI @mattsse could you please clarify:

the title of the issue mentions call and call_end, while the description mentions create and create_end. Which ones should be worked?

**Comment by rakita** [comment]
done
