### ISSUE TITLE
bumping alloy-primitives breaks reth build

### ISSUE THREAD

**Issue by Qumeric** [bluealloy/revm#882]
this commit https://github.com/bluealloy/revm/commit/b00ebab8b3477f87e3d876a11b8f18d00a8f4103 in reth_freeze branch

I cannot build because I get mismatched version of alloy-primitives, reth still depends on 0.4. Even latest reth alpha uses this branch, main too.

I am trying to build with patch but have no luck so far for some reason

**Comment by rakita** [comment]
This was fast! Bump for revm+alloy is upcoming  https://github.com/paradigmxyz/reth/pull/5557

**Comment by Qumeric** [comment]
I think I was unlucky enough to start updating reth around 5 minutes after this commit

Thanks for the update
