### ISSUE TITLE
Bug in ecrecover precompile execution with k256

### ISSUE THREAD

**Issue by ufoscout** [bluealloy/revm#886]
The `ecrecover` precompile returns a wrong result with k256 but it works as expected with secp256k1.
For example, when `test_ecrecover` function of the below solidity contract is called, then:
- with secp256k1 feature enabled the ExecutionResult output is `Call(Bytes(0x000000000000000000000000228b2b113f2f1c6070991d2beca3db0f395158f4))`
- with secp256k1 feature disabled the ExecutionResult output is `Call(Bytes(0x0000000000000000000000000000000000000000000000000000000000000000))`

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.17;

contract TestContractWithPrecompiles {

    // should return 0x228b2b113f2f1c6070991d2beca3db0f395158f4
    function test_ecrecover() public pure returns (address) {
        bytes32 _hash = 0x5cc4cee58087de1a2ea481fe9c65c92adc27cff464b7f00a486dc9bf6bb8efb3;
        bytes32 _r = 0x32573a0b258f251971a4ec35511c018a7e7bf75a5886534b48d12e47263048a2;
        bytes32 _s = 0xfe6e03543955255e235388b224704555fd036a954d3ee6dd030d9d1fea1830d7;
        uint8 _v = 0x1c;
        return (ecrecover(_hash, _v, _r, _s));
    }
}
```

Tested with REVM 3.5.0

**Comment by rakita** [comment]
Can you check what version of k256 are you binding to, there was this issue: https://github.com/bluealloy/revm/pull/870 with k256 minor version bump

**Comment by ufoscout** [comment]
@rakita it is `k256` version `0.13.2`

**Comment by ufoscout** [comment]
I did a couple of tests and if I downgrade to `k256` version `0.13.1` the bug disappears

**Comment by rakita** [comment]
@ufoscout just lock k256 to previous version 0.13.1
