### ISSUE TITLE
Add `prepend_state` function to BundleState

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#904]
There was a need in reth to prepend state. This could be done with extend and removal of N reverts but cleaner solution is to add function directly to the BundleState.

So test is to add this to revm and cherry-pick it to reth_frozen branch/PR https://github.com/bluealloy/revm/pull/875 as this is currently used branch by reth/foundry and finally update it inside reth.

https://github.com/paradigmxyz/reth/pull/5683/files#diff-b80f08909adc9d005f5b75ef45b52d1f72fc935e96712f363513924e2cd34bb2R359-R368

**Comment by peyha** [comment]
Seems like a really good first issue, I'll do it!

**Comment by rakita** [comment]
@peyha gg

**Comment by peyha** [comment]
I will try to cherry-pick the update to the reth_frozen branch and update reth accordingly this week

**Comment by rakita** [comment]
> nch and update reth accordingly this w

Dont bother a lot with it, we expect to have transition in next few weeks (maybe month)
