### ISSUE TITLE
external_fields: Inspector not hooking the outer most frame

### ISSUE THREAD

**Issue by publicqi** [bluealloy/revm#936]
The current implementation in external_fields branch does not hook `create_first_frame` and `first_frame_return`.

https://github.com/bluealloy/revm/blob/external_field/crates/revm/src/inspector/handler_register.rs

**Comment by rakita** [comment]
> The current implementation in external_fields branch does not hook `create_first_frame` and `first_frame_return`.
> 
> https://github.com/bluealloy/revm/blob/external_field/crates/revm/src/inspector/handler_register.rs

Aha you mean `Inspector` does not hook those handlers, but what does `Inspector` need them for, or is this your use case?

**Comment by publicqi** [comment]
🤔️ Do you mean the initial call (entrypoint of the tx) should not be hooked by Inspector `call` function? The thing is that the behavior of the current inspector is not coherent with the old one (master branch). For example, `initialize_interp` is not called in the main frame.

**Comment by rakita** [comment]
> 🤔️ Do you mean the initial call (entrypoint of the tx) should not be hooked by Inspector `call` function? The thing is that the behavior of the current inspector is not coherent with the old one (master branch).
> 
> For example, IIRC `initialize_interp` is not called in the main frame. I think `initialize_interp` should be invoked for every new interpreter? But it's now imbalanced I'm sure of.

That is true, it should be changed, thats good catch

**Comment by rakita** [comment]
Added handlers for it
