### ISSUE TITLE
Add StorageRead journal entry

### ISSUE THREAD

**Issue by zemse** [bluealloy/revm#945]
Currently, if a storage slot is SLOADed multiple times, the StorageChange journal entry cannot help to detect it.

This causes the following issue in Anvil https://github.com/foundry-rs/foundry/issues/6691.

Journaling storage reads can be helpful to fix this problem.

**Comment by rakita** [comment]
> Currently, if a storage slot is SLOADed multiple times, the StorageChange journal entry cannot help to detect it.
> 
> This causes the following issue in Anvil [foundry-rs/foundry#6691](https://github.com/foundry-rs/foundry/issues/6691).
> 
> Journaling storage reads can be helpful to fix this problem.

Doesnt make sense to add in evm, journal entry is there for evm to handle warm load or changes to storage and orbitrary sloads.

You would need to find other way to solve this in anvil.
