### ISSUE TITLE
Use B256 instead of U256 in access list keys

### ISSUE THREAD

**Issue by DaniPopes** [bluealloy/revm#966]
Both Reth and Foundry use `B256` and have to use utilities to convert to `U256`:
- https://github.com/foundry-rs/foundry/blob/fdaed8603fc330cbc94c936f15594bccdc381225/crates/anvil/core/src/eth/utils.rs#L19
- https://github.com/paradigmxyz/reth/blob/56a3548915ec1d369ddf3067911fb730939e63f8/crates/primitives/src/transaction/access_list.rs#L47C1-L47C1

I think the bigger problem here is that Revm uses `U256` for all storage slot key and values, which has a different memory layout than `B256`.

**Comment by rakita** [comment]
U256 is used as the stack in revm is U256 and most of the instructions are done easier on u256 so the storage keys are all in u256. 

There is a possible discussion if we would like for storage keys to be B256 types, then we do transition from stack U256 to B256 when SLOT/STORE are used but I feel that there will be slight downsides than the benefits.

I think the very beneficial thing for this will be Generics over Transaction: https://github.com/bluealloy/revm/issues/916
would make this a lot easier to do.

**Comment by rakita** [comment]
Will close this in favor of https://github.com/bluealloy/revm/issues/916
