### ISSUE TITLE
Conver Optimism panic into graceful error

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#967]
if the encoded tx field is missing transact currently panics:

https://github.com/bluealloy/revm/blob/b9ecc0034ff73f97c7cb25f4b3afb609b0fc0ea5/crates/revm/src/evm_impl.rs#L398-L398

https://github.com/bluealloy/revm/blob/b9ecc0034ff73f97c7cb25f4b3afb609b0fc0ea5/crates/revm/src/evm_impl.rs#L398-L398

this should be an error instead, perhaps like:

https://github.com/bluealloy/revm/blob/b9ecc0034ff73f97c7cb25f4b3afb609b0fc0ea5/crates/primitives/src/result.rs#L249-L250

ref https://github.com/paradigmxyz/reth/issues/6008

**Comment by rakita** [comment]
As we want to phase out the feature but retain present optimism behaviour imo it would be good to add
`Error::Custom(String)` to main revm Error: https://github.com/bluealloy/revm/blob/main/crates/primitives/src/result.rs#L131

This could be temporary as we should introduce some generic for error to work with the custom handler, but atm I am not sure where to tie it so String will do the job.
