### ISSUE TITLE
Valid `JUMPDEST`s inaccessbile if inside `PUSH` bytes

### ISSUE THREAD

**Issue by brockelmore** [bluealloy/revm#97]
According to  `geth`'s [`opJump`](https://github.com/ethereum/go-ethereum/blob/b1e72f7ea998ad662166bcf23705ca59cf81e925/core/vm/instructions.go#L535-L545) implementation, it is valid to have a `JUMPDEST` inside a `PUSHN`, ([see here](https://github.com/ethereum/go-ethereum/blob/b1e72f7ea998ad662166bcf23705ca59cf81e925/core/vm/contract.go#L85-L97)). Geth doesn't do analysis and just checks at runtime if its a valid jump.

The analysis module here shouldn't skip pushbytes when checking for valid jump destinations.

**Comment by brockelmore** [comment]
disregard im wrong

**Comment by rakita** [comment]
I had a lot of this kind of moments 😄
