### ISSUE TITLE
Mocking storage with constant return

### ISSUE THREAD

**Issue by olegggatttor** [bluealloy/revm#977]
Hey! Is it possible to mock access to storage with constant return? E.g., I have some token, and I want it to always return `UINT256::MAX` when I ask for `balance`/`allowance.`

**Comment by rakita** [comment]
You can change the value in Database impl that you use, if this is no enough you can go even lower and 
With `EvmBuilder` (`main` branch) override any instruction.

```
Evm::builder().
.append_handler_register(|h| {
     spec_to_generic!(handler.spec.id, {
            // and modify handler.instruction_table on SLOAD with logic that you need
      }
}
```

**Comment by olegggatttor** [comment]
Great, thanks!
